// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimFranchise = `-- name: ClaimFranchise :exec
update franchises set user_id = $1, invite_token = null where id = $2
`

type ClaimFranchiseParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

// Links the account and uses up the invite link.
func (q *Queries) ClaimFranchise(ctx context.Context, arg ClaimFranchiseParams) error {
	_, err := q.db.Exec(ctx, claimFranchise, arg.UserID, arg.ID)
	return err
}

const createUser = `-- name: CreateUser :one
insert into users (email, password_hash) values ($1, $2) returning id, email, password_hash, sessions_valid_from, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.SessionsValidFrom,
		&i.CreatedAt,
	)
	return i, err
}

const getFranchiseByUser = `-- name: GetFranchiseByUser :one
select id, dynasty_id, name, manager_name, slug, invite_token, is_commissioner, user_id from franchises where user_id = $1
`

func (q *Queries) GetFranchiseByUser(ctx context.Context, userID pgtype.UUID) (Franchise, error) {
	row := q.db.QueryRow(ctx, getFranchiseByUser, userID)
	var i Franchise
	err := row.Scan(
		&i.ID,
		&i.DynastyID,
		&i.Name,
		&i.ManagerName,
		&i.Slug,
		&i.InviteToken,
		&i.IsCommissioner,
		&i.UserID,
	)
	return i, err
}

const getSecret = `-- name: GetSecret :one
select value from secrets where name = $1
`

func (q *Queries) GetSecret(ctx context.Context, name string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSecret, name)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const getUser = `-- name: GetUser :one
select id, email, password_hash, sessions_valid_from, created_at from users where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.SessionsValidFrom,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_hash, sessions_valid_from, created_at from users where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.SessionsValidFrom,
		&i.CreatedAt,
	)
	return i, err
}

const insertSecret = `-- name: InsertSecret :exec
insert into secrets (name, value) values ($1, $2) on conflict (name) do nothing
`

type InsertSecretParams struct {
	Name  string `json:"name"`
	Value []byte `json:"value"`
}

// Keeps the first value written if two servers start at once.
func (q *Queries) InsertSecret(ctx context.Context, arg InsertSecretParams) error {
	_, err := q.db.Exec(ctx, insertSecret, arg.Name, arg.Value)
	return err
}

const listInvites = `-- name: ListInvites :many
select f.id, f.dynasty_id, f.name, f.manager_name, f.slug, f.invite_token, f.is_commissioner, f.user_id, coalesce(u.email, '')::text as email
from franchises f
left join users u on u.id = f.user_id
where f.dynasty_id = $1
order by f.name
`

type ListInvitesRow struct {
	ID             pgtype.UUID `json:"id"`
	DynastyID      pgtype.UUID `json:"dynasty_id"`
	Name           string      `json:"name"`
	ManagerName    string      `json:"manager_name"`
	Slug           string      `json:"slug"`
	InviteToken    pgtype.Text `json:"-"`
	IsCommissioner bool        `json:"is_commissioner"`
	UserID         pgtype.UUID `json:"user_id"`
	Email          string      `json:"email"`
}

func (q *Queries) ListInvites(ctx context.Context, dynastyID pgtype.UUID) ([]ListInvitesRow, error) {
	rows, err := q.db.Query(ctx, listInvites, dynastyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitesRow{}
	for rows.Next() {
		var i ListInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.DynastyID,
			&i.Name,
			&i.ManagerName,
			&i.Slug,
			&i.InviteToken,
			&i.IsCommissioner,
			&i.UserID,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserCredentials = `-- name: SetUserCredentials :exec
update users set email = $1, password_hash = $2, sessions_valid_from = now()
where id = $3
`

type SetUserCredentialsParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	ID           pgtype.UUID `json:"id"`
}

// Changing credentials signs out everything issued before now.
func (q *Queries) SetUserCredentials(ctx context.Context, arg SetUserCredentialsParams) error {
	_, err := q.db.Exec(ctx, setUserCredentials, arg.Email, arg.PasswordHash, arg.ID)
	return err
}
