// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: draft.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDraftLeague = `-- name: AddDraftLeague :exec
insert into draft_leagues (draft_id, league_id) values ($1, $2)
`

type AddDraftLeagueParams struct {
	DraftID  pgtype.UUID `json:"draft_id"`
	LeagueID pgtype.UUID `json:"league_id"`
}

func (q *Queries) AddDraftLeague(ctx context.Context, arg AddDraftLeagueParams) error {
	_, err := q.db.Exec(ctx, addDraftLeague, arg.DraftID, arg.LeagueID)
	return err
}

const clearDraftAutopick = `-- name: ClearDraftAutopick :exec
delete from draft_autopick where draft_id = $1 and franchise_id = $2
`

type ClearDraftAutopickParams struct {
	DraftID     pgtype.UUID `json:"draft_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
}

func (q *Queries) ClearDraftAutopick(ctx context.Context, arg ClearDraftAutopickParams) error {
	_, err := q.db.Exec(ctx, clearDraftAutopick, arg.DraftID, arg.FranchiseID)
	return err
}

const clearDraftPick = `-- name: ClearDraftPick :exec
update draft_picks set player_id = null, league_id = null, picked_at = null, auto_picked = false, skipped_at = null, passed_at = null
where id = $1
`

func (q *Queries) ClearDraftPick(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearDraftPick, id)
	return err
}

const clearDraftQueue = `-- name: ClearDraftQueue :exec
delete from draft_queue where draft_id = $1 and franchise_id = $2
`

type ClearDraftQueueParams struct {
	DraftID     pgtype.UUID `json:"draft_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
}

func (q *Queries) ClearDraftQueue(ctx context.Context, arg ClearDraftQueueParams) error {
	_, err := q.db.Exec(ctx, clearDraftQueue, arg.DraftID, arg.FranchiseID)
	return err
}

const createDraft = `-- name: CreateDraft :one
insert into drafts (dynasty_id, name, kind, year, pick_clock_seconds, is_placeholder)
values ($1, $2, $3, $4, $5, $6)
returning id, dynasty_id, name, kind, year, status, pick_clock_seconds, clock_expires_at, created_at, completed_at, is_placeholder
`

type CreateDraftParams struct {
	DynastyID        pgtype.UUID `json:"dynasty_id"`
	Name             string      `json:"name"`
	Kind             string      `json:"kind"`
	Year             int32       `json:"year"`
	PickClockSeconds int32       `json:"pick_clock_seconds"`
	IsPlaceholder    bool        `json:"is_placeholder"`
}

func (q *Queries) CreateDraft(ctx context.Context, arg CreateDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, createDraft,
		arg.DynastyID,
		arg.Name,
		arg.Kind,
		arg.Year,
		arg.PickClockSeconds,
		arg.IsPlaceholder,
	)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.DynastyID,
		&i.Name,
		&i.Kind,
		&i.Year,
		&i.Status,
		&i.PickClockSeconds,
		&i.ClockExpiresAt,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.IsPlaceholder,
	)
	return i, err
}

const deleteDraft = `-- name: DeleteDraft :exec
delete from drafts where id = $1
`

func (q *Queries) DeleteDraft(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDraft, id)
	return err
}

const deleteDraftPick = `-- name: DeleteDraftPick :exec
delete from draft_picks where id = $1 and draft_id = $2
`

type DeleteDraftPickParams struct {
	ID      pgtype.UUID `json:"id"`
	DraftID pgtype.UUID `json:"draft_id"`
}

func (q *Queries) DeleteDraftPick(ctx context.Context, arg DeleteDraftPickParams) error {
	_, err := q.db.Exec(ctx, deleteDraftPick, arg.ID, arg.DraftID)
	return err
}

const getDraft = `-- name: GetDraft :one
select id, dynasty_id, name, kind, year, status, pick_clock_seconds, clock_expires_at, created_at, completed_at, is_placeholder from drafts where id = $1
`

func (q *Queries) GetDraft(ctx context.Context, id pgtype.UUID) (Draft, error) {
	row := q.db.QueryRow(ctx, getDraft, id)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.DynastyID,
		&i.Name,
		&i.Kind,
		&i.Year,
		&i.Status,
		&i.PickClockSeconds,
		&i.ClockExpiresAt,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.IsPlaceholder,
	)
	return i, err
}

const getDraftPick = `-- name: GetDraftPick :one
select id, draft_id, round, position, original_franchise_id, current_franchise_id, player_id, league_id, picked_at, auto_picked, skipped_at, passed_at from draft_picks where id = $1
`

func (q *Queries) GetDraftPick(ctx context.Context, id pgtype.UUID) (DraftPick, error) {
	row := q.db.QueryRow(ctx, getDraftPick, id)
	var i DraftPick
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.Round,
		&i.Position,
		&i.OriginalFranchiseID,
		&i.CurrentFranchiseID,
		&i.PlayerID,
		&i.LeagueID,
		&i.PickedAt,
		&i.AutoPicked,
		&i.SkippedAt,
		&i.PassedAt,
	)
	return i, err
}

const insertDraftPick = `-- name: InsertDraftPick :exec
insert into draft_picks (draft_id, round, position, original_franchise_id, current_franchise_id)
values ($1, $2, $3, $4, $5)
`

type InsertDraftPickParams struct {
	DraftID             pgtype.UUID `json:"draft_id"`
	Round               int32       `json:"round"`
	Position            int32       `json:"position"`
	OriginalFranchiseID pgtype.UUID `json:"original_franchise_id"`
	CurrentFranchiseID  pgtype.UUID `json:"current_franchise_id"`
}

func (q *Queries) InsertDraftPick(ctx context.Context, arg InsertDraftPickParams) error {
	_, err := q.db.Exec(ctx, insertDraftPick,
		arg.DraftID,
		arg.Round,
		arg.Position,
		arg.OriginalFranchiseID,
		arg.CurrentFranchiseID,
	)
	return err
}

const insertDraftQueue = `-- name: InsertDraftQueue :exec
insert into draft_queue (draft_id, franchise_id, player_id, rank)
values ($1, $2, $3, $4)
`

type InsertDraftQueueParams struct {
	DraftID     pgtype.UUID `json:"draft_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
	PlayerID    pgtype.UUID `json:"player_id"`
	Rank        int32       `json:"rank"`
}

func (q *Queries) InsertDraftQueue(ctx context.Context, arg InsertDraftQueueParams) error {
	_, err := q.db.Exec(ctx, insertDraftQueue,
		arg.DraftID,
		arg.FranchiseID,
		arg.PlayerID,
		arg.Rank,
	)
	return err
}

const lastMadeDraftPick = `-- name: LastMadeDraftPick :one
select id, draft_id, round, position, original_franchise_id, current_franchise_id, player_id, league_id, picked_at, auto_picked, skipped_at, passed_at from draft_picks
where draft_id = $1 and player_id is not null
order by picked_at desc, position desc
limit 1
`

func (q *Queries) LastMadeDraftPick(ctx context.Context, draftID pgtype.UUID) (DraftPick, error) {
	row := q.db.QueryRow(ctx, lastMadeDraftPick, draftID)
	var i DraftPick
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.Round,
		&i.Position,
		&i.OriginalFranchiseID,
		&i.CurrentFranchiseID,
		&i.PlayerID,
		&i.LeagueID,
		&i.PickedAt,
		&i.AutoPicked,
		&i.SkippedAt,
		&i.PassedAt,
	)
	return i, err
}

const leagueHasOpenDraft = `-- name: LeagueHasOpenDraft :one
select exists (
  select 1 from drafts d
  join draft_leagues dl on dl.draft_id = d.id
  where dl.league_id = $1 and d.status in ('live', 'paused')
)
`

func (q *Queries) LeagueHasOpenDraft(ctx context.Context, leagueID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, leagueHasOpenDraft, leagueID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAutoPickCandidates = `-- name: ListAutoPickCandidates :many
select p.id
from players p
join (select ps.player_id, sum(ps.points) as points
      from player_seasons ps
      where ps.competition = $1 and ps.league = '' and ps.points is not null
        and ps.year = (select max(s.year) from stat_seasons s where s.competition = $1)
      group by ps.player_id) scored on scored.player_id = p.id
where p.competition = $1
  and not exists (select 1 from roster_entries r where r.player_id = p.id)
order by scored.points desc, p.id
limit $2
`

type ListAutoPickCandidatesParams struct {
	Competition string `json:"competition"`
	PageSize    int32  `json:"page_size"`
}

// The best players nobody has rostered in one sport, by fantasy points in
// its latest season under the rules of the league here: who auto pick
// chooses among when a franchise's queue is empty.
func (q *Queries) ListAutoPickCandidates(ctx context.Context, arg ListAutoPickCandidatesParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAutoPickCandidates, arg.Competition, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftAutopick = `-- name: ListDraftAutopick :many
select franchise_id from draft_autopick where draft_id = $1 order by franchise_id
`

func (q *Queries) ListDraftAutopick(ctx context.Context, draftID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listDraftAutopick, draftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var franchise_id pgtype.UUID
		if err := rows.Scan(&franchise_id); err != nil {
			return nil, err
		}
		items = append(items, franchise_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftLeagues = `-- name: ListDraftLeagues :many
select l.id, l.dynasty_id, l.competition, l.name, l.settings, l.last_draft_at from leagues l
join draft_leagues dl on dl.league_id = l.id
where dl.draft_id = $1
`

func (q *Queries) ListDraftLeagues(ctx context.Context, draftID pgtype.UUID) ([]League, error) {
	rows, err := q.db.Query(ctx, listDraftLeagues, draftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []League{}
	for rows.Next() {
		var i League
		if err := rows.Scan(
			&i.ID,
			&i.DynastyID,
			&i.Competition,
			&i.Name,
			&i.Settings,
			&i.LastDraftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftPicks = `-- name: ListDraftPicks :many
select k.id, k.draft_id, k.round, k.position, k.original_franchise_id, k.current_franchise_id, k.player_id, k.league_id, k.picked_at, k.auto_picked, k.skipped_at, k.passed_at,
       coalesce(p.full_name, '')::text    as player_name,
       coalesce(p.positions, '{}')::text[] as player_positions,
       coalesce(p.headshot_url, '')::text as player_headshot,
       coalesce(l.competition, '')::text  as competition
from draft_picks k
left join players p on p.id = k.player_id
left join leagues l on l.id = k.league_id
where k.draft_id = $1
order by k.position
`

type ListDraftPicksRow struct {
	ID                  pgtype.UUID        `json:"id"`
	DraftID             pgtype.UUID        `json:"draft_id"`
	Round               int32              `json:"round"`
	Position            int32              `json:"position"`
	OriginalFranchiseID pgtype.UUID        `json:"original_franchise_id"`
	CurrentFranchiseID  pgtype.UUID        `json:"current_franchise_id"`
	PlayerID            pgtype.UUID        `json:"player_id"`
	LeagueID            pgtype.UUID        `json:"league_id"`
	PickedAt            pgtype.Timestamptz `json:"picked_at"`
	AutoPicked          bool               `json:"auto_picked"`
	SkippedAt           pgtype.Timestamptz `json:"skipped_at"`
	PassedAt            pgtype.Timestamptz `json:"passed_at"`
	PlayerName          string             `json:"player_name"`
	PlayerPositions     []string           `json:"player_positions"`
	PlayerHeadshot      string             `json:"player_headshot"`
	Competition         string             `json:"competition"`
}

func (q *Queries) ListDraftPicks(ctx context.Context, draftID pgtype.UUID) ([]ListDraftPicksRow, error) {
	rows, err := q.db.Query(ctx, listDraftPicks, draftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftPicksRow{}
	for rows.Next() {
		var i ListDraftPicksRow
		if err := rows.Scan(
			&i.ID,
			&i.DraftID,
			&i.Round,
			&i.Position,
			&i.OriginalFranchiseID,
			&i.CurrentFranchiseID,
			&i.PlayerID,
			&i.LeagueID,
			&i.PickedAt,
			&i.AutoPicked,
			&i.SkippedAt,
			&i.PassedAt,
			&i.PlayerName,
			&i.PlayerPositions,
			&i.PlayerHeadshot,
			&i.Competition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftQueue = `-- name: ListDraftQueue :many
select q.player_id, q.rank, p.full_name, p.positions, p.competition, p.status, p.headshot_url,
       coalesce(t.abbrev, '')::text as team_abbrev
from draft_queue q
join players p on p.id = q.player_id
left join pro_teams t on t.id = p.pro_team_id
where q.draft_id = $1 and q.franchise_id = $2
order by q.rank
`

type ListDraftQueueParams struct {
	DraftID     pgtype.UUID `json:"draft_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
}

type ListDraftQueueRow struct {
	PlayerID    pgtype.UUID `json:"player_id"`
	Rank        int32       `json:"rank"`
	FullName    string      `json:"full_name"`
	Positions   []string    `json:"positions"`
	Competition string      `json:"competition"`
	Status      string      `json:"status"`
	HeadshotUrl string      `json:"headshot_url"`
	TeamAbbrev  string      `json:"team_abbrev"`
}

func (q *Queries) ListDraftQueue(ctx context.Context, arg ListDraftQueueParams) ([]ListDraftQueueRow, error) {
	rows, err := q.db.Query(ctx, listDraftQueue, arg.DraftID, arg.FranchiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftQueueRow{}
	for rows.Next() {
		var i ListDraftQueueRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.Rank,
			&i.FullName,
			&i.Positions,
			&i.Competition,
			&i.Status,
			&i.HeadshotUrl,
			&i.TeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrafts = `-- name: ListDrafts :many
select d.id, d.dynasty_id, d.name, d.kind, d.year, d.status, d.pick_clock_seconds, d.clock_expires_at, d.created_at, d.completed_at, d.is_placeholder,
       (select coalesce(array_agg(l.competition), '{}')::text[]
        from draft_leagues dl join leagues l on l.id = dl.league_id
        where dl.draft_id = d.id) as competitions,
       (select count(*) from draft_picks k where k.draft_id = d.id) as picks,
       (select count(*) from draft_picks k where k.draft_id = d.id and k.player_id is not null) as picks_made
from drafts d
where d.dynasty_id = $1
order by d.created_at desc
`

type ListDraftsRow struct {
	ID               pgtype.UUID        `json:"id"`
	DynastyID        pgtype.UUID        `json:"dynasty_id"`
	Name             string             `json:"name"`
	Kind             string             `json:"kind"`
	Year             int32              `json:"year"`
	Status           string             `json:"status"`
	PickClockSeconds int32              `json:"pick_clock_seconds"`
	ClockExpiresAt   pgtype.Timestamptz `json:"clock_expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	IsPlaceholder    bool               `json:"is_placeholder"`
	Competitions     []string           `json:"competitions"`
	Picks            int64              `json:"picks"`
	PicksMade        int64              `json:"picks_made"`
}

func (q *Queries) ListDrafts(ctx context.Context, dynastyID pgtype.UUID) ([]ListDraftsRow, error) {
	rows, err := q.db.Query(ctx, listDrafts, dynastyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftsRow{}
	for rows.Next() {
		var i ListDraftsRow
		if err := rows.Scan(
			&i.ID,
			&i.DynastyID,
			&i.Name,
			&i.Kind,
			&i.Year,
			&i.Status,
			&i.PickClockSeconds,
			&i.ClockExpiresAt,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.IsPlaceholder,
			&i.Competitions,
			&i.Picks,
			&i.PicksMade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredDrafts = `-- name: ListExpiredDrafts :many
select id from drafts where status = 'live' and clock_expires_at < now()
`

func (q *Queries) ListExpiredDrafts(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredDrafts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDraft = `-- name: LockDraft :one
select id, dynasty_id, name, kind, year, status, pick_clock_seconds, clock_expires_at, created_at, completed_at, is_placeholder from drafts where id = $1 for update
`

// Serializes everything that changes one draft.
func (q *Queries) LockDraft(ctx context.Context, id pgtype.UUID) (Draft, error) {
	row := q.db.QueryRow(ctx, lockDraft, id)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.DynastyID,
		&i.Name,
		&i.Kind,
		&i.Year,
		&i.Status,
		&i.PickClockSeconds,
		&i.ClockExpiresAt,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.IsPlaceholder,
	)
	return i, err
}

const makeDraftPick = `-- name: MakeDraftPick :exec
update draft_picks set
  player_id   = $1,
  league_id   = $2,
  picked_at   = now(),
  auto_picked = $3
where id = $4
`

type MakeDraftPickParams struct {
	PlayerID   pgtype.UUID `json:"player_id"`
	LeagueID   pgtype.UUID `json:"league_id"`
	AutoPicked bool        `json:"auto_picked"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) MakeDraftPick(ctx context.Context, arg MakeDraftPickParams) error {
	_, err := q.db.Exec(ctx, makeDraftPick,
		arg.PlayerID,
		arg.LeagueID,
		arg.AutoPicked,
		arg.ID,
	)
	return err
}

const markLeaguesDrafted = `-- name: MarkLeaguesDrafted :exec
update leagues set last_draft_at = now()
where id in (select league_id from draft_leagues where draft_id = $1)
`

// Players who were in the pool before this moment become free agents.
func (q *Queries) MarkLeaguesDrafted(ctx context.Context, draftID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markLeaguesDrafted, draftID)
	return err
}

const passDraftPick = `-- name: PassDraftPick :exec
update draft_picks set passed_at = now() where id = $1
`

func (q *Queries) PassDraftPick(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, passDraftPick, id)
	return err
}

const removeFromDraftQueues = `-- name: RemoveFromDraftQueues :exec
delete from draft_queue where draft_id = $1 and player_id = $2
`

type RemoveFromDraftQueuesParams struct {
	DraftID  pgtype.UUID `json:"draft_id"`
	PlayerID pgtype.UUID `json:"player_id"`
}

// A drafted player leaves everyone's queue.
func (q *Queries) RemoveFromDraftQueues(ctx context.Context, arg RemoveFromDraftQueuesParams) error {
	_, err := q.db.Exec(ctx, removeFromDraftQueues, arg.DraftID, arg.PlayerID)
	return err
}

const scheduleDraft = `-- name: ScheduleDraft :exec
update drafts set is_placeholder = false where id = $1
`

func (q *Queries) ScheduleDraft(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, scheduleDraft, id)
	return err
}

const setDraftAutopick = `-- name: SetDraftAutopick :exec
insert into draft_autopick (draft_id, franchise_id) values ($1, $2)
on conflict do nothing
`

type SetDraftAutopickParams struct {
	DraftID     pgtype.UUID `json:"draft_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
}

func (q *Queries) SetDraftAutopick(ctx context.Context, arg SetDraftAutopickParams) error {
	_, err := q.db.Exec(ctx, setDraftAutopick, arg.DraftID, arg.FranchiseID)
	return err
}

const setDraftClock = `-- name: SetDraftClock :exec
update drafts set pick_clock_seconds = $1 where id = $2
`

type SetDraftClockParams struct {
	PickClockSeconds int32       `json:"pick_clock_seconds"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) SetDraftClock(ctx context.Context, arg SetDraftClockParams) error {
	_, err := q.db.Exec(ctx, setDraftClock, arg.PickClockSeconds, arg.ID)
	return err
}

const setDraftStatus = `-- name: SetDraftStatus :exec
update drafts set
  status           = $1,
  clock_expires_at = $2,
  completed_at     = case when $1 = 'complete' then now() else null end
where id = $3
`

type SetDraftStatusParams struct {
	Status         string             `json:"status"`
	ClockExpiresAt pgtype.Timestamptz `json:"clock_expires_at"`
	ID             pgtype.UUID        `json:"id"`
}

func (q *Queries) SetDraftStatus(ctx context.Context, arg SetDraftStatusParams) error {
	_, err := q.db.Exec(ctx, setDraftStatus, arg.Status, arg.ClockExpiresAt, arg.ID)
	return err
}

const skipDraftPick = `-- name: SkipDraftPick :exec
update draft_picks set skipped_at = now() where id = $1
`

func (q *Queries) SkipDraftPick(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, skipDraftPick, id)
	return err
}

const startupDraftExists = `-- name: StartupDraftExists :one
select exists (
  select 1 from drafts d
  join draft_leagues dl on dl.draft_id = d.id
  where d.kind = 'startup' and dl.league_id = $1
)
`

// Whether a league has ever been in a startup draft, finished or not.
func (q *Queries) StartupDraftExists(ctx context.Context, leagueID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, startupDraftExists, leagueID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateDraftPickSlot = `-- name: UpdateDraftPickSlot :exec
update draft_picks set
  round                 = $1,
  position              = $2,
  original_franchise_id = $3,
  current_franchise_id  = $4
where id = $5 and draft_id = $6
`

type UpdateDraftPickSlotParams struct {
	Round               int32       `json:"round"`
	Position            int32       `json:"position"`
	OriginalFranchiseID pgtype.UUID `json:"original_franchise_id"`
	CurrentFranchiseID  pgtype.UUID `json:"current_franchise_id"`
	ID                  pgtype.UUID `json:"id"`
	DraftID             pgtype.UUID `json:"draft_id"`
}

func (q *Queries) UpdateDraftPickSlot(ctx context.Context, arg UpdateDraftPickSlotParams) error {
	_, err := q.db.Exec(ctx, updateDraftPickSlot,
		arg.Round,
		arg.Position,
		arg.OriginalFranchiseID,
		arg.CurrentFranchiseID,
		arg.ID,
		arg.DraftID,
	)
	return err
}
