// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dynasty.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDynasty = `-- name: CreateDynasty :one
insert into dynasties (name, settings) values ($1, $2) returning id, name, settings, created_at
`

type CreateDynastyParams struct {
	Name     string          `json:"name"`
	Settings json.RawMessage `json:"settings"`
}

func (q *Queries) CreateDynasty(ctx context.Context, arg CreateDynastyParams) (Dynasty, error) {
	row := q.db.QueryRow(ctx, createDynasty, arg.Name, arg.Settings)
	var i Dynasty
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const createFranchise = `-- name: CreateFranchise :one
insert into franchises (dynasty_id, name, manager_name, slug, invite_token, is_commissioner)
values ($1, $2, $3, $4, $5, $6)
returning id, dynasty_id, name, manager_name, slug, invite_token, is_commissioner, user_id
`

type CreateFranchiseParams struct {
	DynastyID      pgtype.UUID `json:"dynasty_id"`
	Name           string      `json:"name"`
	ManagerName    string      `json:"manager_name"`
	Slug           string      `json:"slug"`
	InviteToken    pgtype.Text `json:"-"`
	IsCommissioner bool        `json:"is_commissioner"`
}

func (q *Queries) CreateFranchise(ctx context.Context, arg CreateFranchiseParams) (Franchise, error) {
	row := q.db.QueryRow(ctx, createFranchise,
		arg.DynastyID,
		arg.Name,
		arg.ManagerName,
		arg.Slug,
		arg.InviteToken,
		arg.IsCommissioner,
	)
	var i Franchise
	err := row.Scan(
		&i.ID,
		&i.DynastyID,
		&i.Name,
		&i.ManagerName,
		&i.Slug,
		&i.InviteToken,
		&i.IsCommissioner,
		&i.UserID,
	)
	return i, err
}

const createLeague = `-- name: CreateLeague :one
insert into leagues (dynasty_id, competition, name, settings)
values ($1, $2, $3, $4)
returning id, dynasty_id, competition, name, settings, last_draft_at
`

type CreateLeagueParams struct {
	DynastyID   pgtype.UUID     `json:"dynasty_id"`
	Competition string          `json:"competition"`
	Name        string          `json:"name"`
	Settings    json.RawMessage `json:"settings"`
}

func (q *Queries) CreateLeague(ctx context.Context, arg CreateLeagueParams) (League, error) {
	row := q.db.QueryRow(ctx, createLeague,
		arg.DynastyID,
		arg.Competition,
		arg.Name,
		arg.Settings,
	)
	var i League
	err := row.Scan(
		&i.ID,
		&i.DynastyID,
		&i.Competition,
		&i.Name,
		&i.Settings,
		&i.LastDraftAt,
	)
	return i, err
}

const getDynasty = `-- name: GetDynasty :one

select id, name, settings, created_at from dynasties order by created_at limit 1
`

// The screens assume a single dynasty per server; the schema does not.
func (q *Queries) GetDynasty(ctx context.Context) (Dynasty, error) {
	row := q.db.QueryRow(ctx, getDynasty)
	var i Dynasty
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const getFranchise = `-- name: GetFranchise :one
select id, dynasty_id, name, manager_name, slug, invite_token, is_commissioner, user_id from franchises where id = $1
`

func (q *Queries) GetFranchise(ctx context.Context, id pgtype.UUID) (Franchise, error) {
	row := q.db.QueryRow(ctx, getFranchise, id)
	var i Franchise
	err := row.Scan(
		&i.ID,
		&i.DynastyID,
		&i.Name,
		&i.ManagerName,
		&i.Slug,
		&i.InviteToken,
		&i.IsCommissioner,
		&i.UserID,
	)
	return i, err
}

const getFranchiseByInvite = `-- name: GetFranchiseByInvite :one
select id, dynasty_id, name, manager_name, slug, invite_token, is_commissioner, user_id from franchises where invite_token = $1::text
`

func (q *Queries) GetFranchiseByInvite(ctx context.Context, inviteToken string) (Franchise, error) {
	row := q.db.QueryRow(ctx, getFranchiseByInvite, inviteToken)
	var i Franchise
	err := row.Scan(
		&i.ID,
		&i.DynastyID,
		&i.Name,
		&i.ManagerName,
		&i.Slug,
		&i.InviteToken,
		&i.IsCommissioner,
		&i.UserID,
	)
	return i, err
}

const getFranchiseBySlug = `-- name: GetFranchiseBySlug :one
select id, dynasty_id, name, manager_name, slug, invite_token, is_commissioner, user_id from franchises where dynasty_id = $1 and slug = $2
`

type GetFranchiseBySlugParams struct {
	DynastyID pgtype.UUID `json:"dynasty_id"`
	Slug      string      `json:"slug"`
}

func (q *Queries) GetFranchiseBySlug(ctx context.Context, arg GetFranchiseBySlugParams) (Franchise, error) {
	row := q.db.QueryRow(ctx, getFranchiseBySlug, arg.DynastyID, arg.Slug)
	var i Franchise
	err := row.Scan(
		&i.ID,
		&i.DynastyID,
		&i.Name,
		&i.ManagerName,
		&i.Slug,
		&i.InviteToken,
		&i.IsCommissioner,
		&i.UserID,
	)
	return i, err
}

const getLeague = `-- name: GetLeague :one
select id, dynasty_id, competition, name, settings, last_draft_at from leagues where id = $1
`

func (q *Queries) GetLeague(ctx context.Context, id pgtype.UUID) (League, error) {
	row := q.db.QueryRow(ctx, getLeague, id)
	var i League
	err := row.Scan(
		&i.ID,
		&i.DynastyID,
		&i.Competition,
		&i.Name,
		&i.Settings,
		&i.LastDraftAt,
	)
	return i, err
}

const listFranchises = `-- name: ListFranchises :many
select id, dynasty_id, name, manager_name, slug, invite_token, is_commissioner, user_id from franchises where dynasty_id = $1 order by name
`

func (q *Queries) ListFranchises(ctx context.Context, dynastyID pgtype.UUID) ([]Franchise, error) {
	rows, err := q.db.Query(ctx, listFranchises, dynastyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Franchise{}
	for rows.Next() {
		var i Franchise
		if err := rows.Scan(
			&i.ID,
			&i.DynastyID,
			&i.Name,
			&i.ManagerName,
			&i.Slug,
			&i.InviteToken,
			&i.IsCommissioner,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeagueCompetitions = `-- name: ListLeagueCompetitions :many
select distinct competition from leagues
`

// The sports anyone here actually plays, across every dynasty.
func (q *Queries) ListLeagueCompetitions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listLeagueCompetitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var competition string
		if err := rows.Scan(&competition); err != nil {
			return nil, err
		}
		items = append(items, competition)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeagues = `-- name: ListLeagues :many
select id, dynasty_id, competition, name, settings, last_draft_at from leagues where dynasty_id = $1
`

func (q *Queries) ListLeagues(ctx context.Context, dynastyID pgtype.UUID) ([]League, error) {
	rows, err := q.db.Query(ctx, listLeagues, dynastyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []League{}
	for rows.Next() {
		var i League
		if err := rows.Scan(
			&i.ID,
			&i.DynastyID,
			&i.Competition,
			&i.Name,
			&i.Settings,
			&i.LastDraftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFranchiseToken = `-- name: SetFranchiseToken :exec
update franchises set invite_token = $1 where id = $2
`

type SetFranchiseTokenParams struct {
	InviteToken pgtype.Text `json:"-"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) SetFranchiseToken(ctx context.Context, arg SetFranchiseTokenParams) error {
	_, err := q.db.Exec(ctx, setFranchiseToken, arg.InviteToken, arg.ID)
	return err
}

const updateDynasty = `-- name: UpdateDynasty :exec
update dynasties set name = $1, settings = $2 where id = $3
`

type UpdateDynastyParams struct {
	Name     string          `json:"name"`
	Settings json.RawMessage `json:"settings"`
	ID       pgtype.UUID     `json:"id"`
}

func (q *Queries) UpdateDynasty(ctx context.Context, arg UpdateDynastyParams) error {
	_, err := q.db.Exec(ctx, updateDynasty, arg.Name, arg.Settings, arg.ID)
	return err
}

const updateFranchise = `-- name: UpdateFranchise :exec
update franchises
set name = $1, manager_name = $2, is_commissioner = $3
where id = $4
`

type UpdateFranchiseParams struct {
	Name           string      `json:"name"`
	ManagerName    string      `json:"manager_name"`
	IsCommissioner bool        `json:"is_commissioner"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateFranchise(ctx context.Context, arg UpdateFranchiseParams) error {
	_, err := q.db.Exec(ctx, updateFranchise,
		arg.Name,
		arg.ManagerName,
		arg.IsCommissioner,
		arg.ID,
	)
	return err
}

const updateLeagueSettings = `-- name: UpdateLeagueSettings :exec
update leagues set settings = $1 where id = $2
`

type UpdateLeagueSettingsParams struct {
	Settings json.RawMessage `json:"settings"`
	ID       pgtype.UUID     `json:"id"`
}

func (q *Queries) UpdateLeagueSettings(ctx context.Context, arg UpdateLeagueSettingsParams) error {
	_, err := q.db.Exec(ctx, updateLeagueSettings, arg.Settings, arg.ID)
	return err
}
