// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePlayerNickname = `-- name: DeletePlayerNickname :exec
delete from player_nicknames where franchise_id = $1 and player_id = $2
`

type DeletePlayerNicknameParams struct {
	FranchiseID pgtype.UUID `json:"franchise_id"`
	PlayerID    pgtype.UUID `json:"player_id"`
}

func (q *Queries) DeletePlayerNickname(ctx context.Context, arg DeletePlayerNicknameParams) error {
	_, err := q.db.Exec(ctx, deletePlayerNickname, arg.FranchiseID, arg.PlayerID)
	return err
}

const getPlayerNickname = `-- name: GetPlayerNickname :one
select coalesce((select nickname from player_nicknames where franchise_id = $1 and player_id = $2), '')::text as nickname
`

type GetPlayerNicknameParams struct {
	FranchiseID pgtype.UUID `json:"franchise_id"`
	PlayerID    pgtype.UUID `json:"player_id"`
}

func (q *Queries) GetPlayerNickname(ctx context.Context, arg GetPlayerNicknameParams) (string, error) {
	row := q.db.QueryRow(ctx, getPlayerNickname, arg.FranchiseID, arg.PlayerID)
	var nickname string
	err := row.Scan(&nickname)
	return nickname, err
}

const listTeamIdentities = `-- name: ListTeamIdentities :many
select ft.franchise_id, ft.league_id, ft.name, ft.image_url, l.competition from franchise_teams ft
join leagues l on l.id = ft.league_id
where l.dynasty_id = $1 order by ft.franchise_id, l.competition
`

type ListTeamIdentitiesRow struct {
	FranchiseID pgtype.UUID `json:"franchise_id"`
	LeagueID    pgtype.UUID `json:"league_id"`
	Name        string      `json:"name"`
	ImageUrl    string      `json:"image_url"`
	Competition string      `json:"competition"`
}

func (q *Queries) ListTeamIdentities(ctx context.Context, dynastyID pgtype.UUID) ([]ListTeamIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, listTeamIdentities, dynastyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamIdentitiesRow{}
	for rows.Next() {
		var i ListTeamIdentitiesRow
		if err := rows.Scan(
			&i.FranchiseID,
			&i.LeagueID,
			&i.Name,
			&i.ImageUrl,
			&i.Competition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movePlayerNicknames = `-- name: MovePlayerNicknames :exec
update player_nicknames n set player_id = $1
where n.player_id = $2
 and not exists (select 1 from player_nicknames k where k.franchise_id = n.franchise_id and k.player_id = $1)
`

type MovePlayerNicknamesParams struct {
	KeepID      pgtype.UUID `json:"keep_id"`
	DuplicateID pgtype.UUID `json:"duplicate_id"`
}

func (q *Queries) MovePlayerNicknames(ctx context.Context, arg MovePlayerNicknamesParams) error {
	_, err := q.db.Exec(ctx, movePlayerNicknames, arg.KeepID, arg.DuplicateID)
	return err
}

const setPlayerNickname = `-- name: SetPlayerNickname :exec
insert into player_nicknames (franchise_id, player_id, nickname) values ($1, $2, $3)
on conflict (franchise_id, player_id) do update set nickname = excluded.nickname
`

type SetPlayerNicknameParams struct {
	FranchiseID pgtype.UUID `json:"franchise_id"`
	PlayerID    pgtype.UUID `json:"player_id"`
	Nickname    string      `json:"nickname"`
}

func (q *Queries) SetPlayerNickname(ctx context.Context, arg SetPlayerNicknameParams) error {
	_, err := q.db.Exec(ctx, setPlayerNickname, arg.FranchiseID, arg.PlayerID, arg.Nickname)
	return err
}

const setTeamIdentity = `-- name: SetTeamIdentity :exec
insert into franchise_teams (franchise_id, league_id, name, image_url)
values ($1, $2, $3, $4)
on conflict (franchise_id, league_id) do update set name = excluded.name, image_url = excluded.image_url
`

type SetTeamIdentityParams struct {
	FranchiseID pgtype.UUID `json:"franchise_id"`
	LeagueID    pgtype.UUID `json:"league_id"`
	Name        string      `json:"name"`
	ImageUrl    string      `json:"image_url"`
}

func (q *Queries) SetTeamIdentity(ctx context.Context, arg SetTeamIdentityParams) error {
	_, err := q.db.Exec(ctx, setTeamIdentity,
		arg.FranchiseID,
		arg.LeagueID,
		arg.Name,
		arg.ImageUrl,
	)
	return err
}

const updateOrganizationIdentity = `-- name: UpdateOrganizationIdentity :exec
update franchises set name = $1, image_url = $2 where id = $3
`

type UpdateOrganizationIdentityParams struct {
	Name     string      `json:"name"`
	ImageUrl string      `json:"image_url"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateOrganizationIdentity(ctx context.Context, arg UpdateOrganizationIdentityParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationIdentity, arg.Name, arg.ImageUrl, arg.ID)
	return err
}
