// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingest.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishIngestRun = `-- name: FinishIngestRun :exec
update ingest_runs set
  finished_at   = now(),
  status        = case when $1::text = '' then 'ok' else 'error' end,
  rows_upserted = $2,
  error         = $1
where id = $3
`

type FinishIngestRunParams struct {
	Error        string `json:"error"`
	RowsUpserted int32  `json:"rows_upserted"`
	ID           int64  `json:"id"`
}

func (q *Queries) FinishIngestRun(ctx context.Context, arg FinishIngestRunParams) error {
	_, err := q.db.Exec(ctx, finishIngestRun, arg.Error, arg.RowsUpserted, arg.ID)
	return err
}

const listIngestRuns = `-- name: ListIngestRuns :many
select id, competition, job, started_at, finished_at, status, rows_upserted, error from ingest_runs order by id desc limit $1
`

func (q *Queries) ListIngestRuns(ctx context.Context, pageSize int32) ([]IngestRun, error) {
	rows, err := q.db.Query(ctx, listIngestRuns, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestRun{}
	for rows.Next() {
		var i IngestRun
		if err := rows.Scan(
			&i.ID,
			&i.Competition,
			&i.Job,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.RowsUpserted,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveRawPayload = `-- name: SaveRawPayload :exec
insert into raw_payloads (url, body) values ($1, $2)
on conflict (url) do update set body = excluded.body, fetched_at = now()
`

type SaveRawPayloadParams struct {
	Url  string `json:"url"`
	Body string `json:"body"`
}

func (q *Queries) SaveRawPayload(ctx context.Context, arg SaveRawPayloadParams) error {
	_, err := q.db.Exec(ctx, saveRawPayload, arg.Url, arg.Body)
	return err
}

const startIngestRun = `-- name: StartIngestRun :one
insert into ingest_runs (competition, job) values ($1, $2)
returning id, started_at
`

type StartIngestRunParams struct {
	Competition string `json:"competition"`
	Job         string `json:"job"`
}

type StartIngestRunRow struct {
	ID        int64              `json:"id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) StartIngestRun(ctx context.Context, arg StartIngestRunParams) (StartIngestRunRow, error) {
	row := q.db.QueryRow(ctx, startIngestRun, arg.Competition, arg.Job)
	var i StartIngestRunRow
	err := row.Scan(&i.ID, &i.StartedAt)
	return i, err
}
