// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Draft struct {
	ID               pgtype.UUID        `json:"id"`
	DynastyID        pgtype.UUID        `json:"dynasty_id"`
	Name             string             `json:"name"`
	Kind             string             `json:"kind"`
	Year             int32              `json:"year"`
	Status           string             `json:"status"`
	PickClockSeconds int32              `json:"pick_clock_seconds"`
	ClockExpiresAt   pgtype.Timestamptz `json:"clock_expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
}

type DraftLeague struct {
	DraftID  pgtype.UUID `json:"draft_id"`
	LeagueID pgtype.UUID `json:"league_id"`
}

type DraftPick struct {
	ID                  pgtype.UUID        `json:"id"`
	DraftID             pgtype.UUID        `json:"draft_id"`
	Round               int32              `json:"round"`
	Position            int32              `json:"position"`
	OriginalFranchiseID pgtype.UUID        `json:"original_franchise_id"`
	CurrentFranchiseID  pgtype.UUID        `json:"current_franchise_id"`
	PlayerID            pgtype.UUID        `json:"player_id"`
	LeagueID            pgtype.UUID        `json:"league_id"`
	PickedAt            pgtype.Timestamptz `json:"picked_at"`
	AutoPicked          bool               `json:"auto_picked"`
	SkippedAt           pgtype.Timestamptz `json:"skipped_at"`
}

type DraftQueue struct {
	DraftID     pgtype.UUID `json:"draft_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
	PlayerID    pgtype.UUID `json:"player_id"`
	Rank        int32       `json:"rank"`
}

type Dynasty struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Settings  json.RawMessage    `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Franchise struct {
	ID             pgtype.UUID `json:"id"`
	DynastyID      pgtype.UUID `json:"dynasty_id"`
	Name           string      `json:"name"`
	ManagerName    string      `json:"manager_name"`
	Slug           string      `json:"slug"`
	InviteToken    pgtype.Text `json:"-"`
	IsCommissioner bool        `json:"is_commissioner"`
	UserID         pgtype.UUID `json:"user_id"`
}

type Game struct {
	ID            pgtype.UUID        `json:"id"`
	Competition   string             `json:"competition"`
	ProviderID    string             `json:"provider_id"`
	Day           pgtype.Date        `json:"day"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	Status        string             `json:"status"`
	HomeTeamID    pgtype.UUID        `json:"home_team_id"`
	AwayTeamID    pgtype.UUID        `json:"away_team_id"`
	StatsSyncedAt pgtype.Timestamptz `json:"stats_synced_at"`
	HomeScore     int32              `json:"home_score"`
	AwayScore     int32              `json:"away_score"`
	Detail        string             `json:"detail"`
}

type IngestRun struct {
	ID           int64              `json:"id"`
	Competition  string             `json:"competition"`
	Job          string             `json:"job"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	Status       string             `json:"status"`
	RowsUpserted int32              `json:"rows_upserted"`
	Error        string             `json:"error"`
}

type League struct {
	ID          pgtype.UUID        `json:"id"`
	DynastyID   pgtype.UUID        `json:"dynasty_id"`
	Competition string             `json:"competition"`
	Name        string             `json:"name"`
	Settings    json.RawMessage    `json:"settings"`
	LastDraftAt pgtype.Timestamptz `json:"last_draft_at"`
}

type Lineup struct {
	LeagueID    pgtype.UUID `json:"league_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
	EffectiveOn pgtype.Date `json:"effective_on"`
}

type LineupEntry struct {
	LeagueID    pgtype.UUID `json:"league_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
	EffectiveOn pgtype.Date `json:"effective_on"`
	Slot        string      `json:"slot"`
	SlotIndex   int32       `json:"slot_index"`
	PlayerID    pgtype.UUID `json:"player_id"`
	CountsFrom  pgtype.Date `json:"counts_from"`
}

type Matchup struct {
	ID              pgtype.UUID `json:"id"`
	PeriodID        pgtype.UUID `json:"period_id"`
	HomeFranchiseID pgtype.UUID `json:"home_franchise_id"`
	AwayFranchiseID pgtype.UUID `json:"away_franchise_id"`
}

type Period struct {
	ID        pgtype.UUID `json:"id"`
	SeasonID  pgtype.UUID `json:"season_id"`
	Seq       int32       `json:"seq"`
	StartsOn  pgtype.Date `json:"starts_on"`
	EndsOn    pgtype.Date `json:"ends_on"`
	IsPlayoff bool        `json:"is_playoff"`
}

type Player struct {
	ID              pgtype.UUID        `json:"id"`
	Competition     string             `json:"competition"`
	Status          string             `json:"status"`
	EligibleSince   pgtype.Timestamptz `json:"eligible_since"`
	FullName        string             `json:"full_name"`
	Positions       []string           `json:"positions"`
	BirthDate       pgtype.Date        `json:"birth_date"`
	ProTeamID       pgtype.UUID        `json:"pro_team_id"`
	Class           string             `json:"class"`
	Note            string             `json:"note"`
	HeadshotUrl     string             `json:"headshot_url"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CareerCheckedAt pgtype.Timestamptz `json:"career_checked_at"`
}

type PlayerExternalID struct {
	Provider   string      `json:"provider"`
	ProviderID string      `json:"provider_id"`
	PlayerID   pgtype.UUID `json:"player_id"`
}

type PlayerSeason struct {
	PlayerID    pgtype.UUID        `json:"player_id"`
	Competition string             `json:"competition"`
	Year        int32              `json:"year"`
	Label       string             `json:"label"`
	Team        string             `json:"team"`
	League      string             `json:"league"`
	Games       int32              `json:"games"`
	Stats       json.RawMessage    `json:"stats"`
	SyncedAt    pgtype.Timestamptz `json:"synced_at"`
}

type ProTeam struct {
	ID          pgtype.UUID `json:"id"`
	Competition string      `json:"competition"`
	ProviderID  string      `json:"provider_id"`
	Abbrev      string      `json:"abbrev"`
	Name        string      `json:"name"`
	LogoUrl     string      `json:"logo_url"`
}

type RawPayload struct {
	Url       string             `json:"url"`
	Body      string             `json:"body"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}

type RosterEntry struct {
	LeagueID    pgtype.UUID        `json:"league_id"`
	FranchiseID pgtype.UUID        `json:"franchise_id"`
	PlayerID    pgtype.UUID        `json:"player_id"`
	List        string             `json:"list"`
	AcquiredVia string             `json:"acquired_via"`
	AcquiredAt  pgtype.Timestamptz `json:"acquired_at"`
	ReservedAt  pgtype.Timestamptz `json:"reserved_at"`
}

type Season struct {
	ID                  pgtype.UUID `json:"id"`
	LeagueID            pgtype.UUID `json:"league_id"`
	Year                int32       `json:"year"`
	StartsOn            pgtype.Date `json:"starts_on"`
	EndsOn              pgtype.Date `json:"ends_on"`
	Status              string      `json:"status"`
	ChampionFranchiseID pgtype.UUID `json:"champion_franchise_id"`
}

type Secret struct {
	Name  string `json:"name"`
	Value []byte `json:"value"`
}

type StatLine struct {
	GameID   pgtype.UUID     `json:"game_id"`
	PlayerID pgtype.UUID     `json:"player_id"`
	Stats    json.RawMessage `json:"stats"`
}

type Trade struct {
	ID         pgtype.UUID        `json:"id"`
	DynastyID  pgtype.UUID        `json:"dynasty_id"`
	Status     string             `json:"status"`
	ProposedBy pgtype.UUID        `json:"proposed_by"`
	Note       string             `json:"note"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

type TradeItem struct {
	ID            pgtype.UUID `json:"id"`
	TradeID       pgtype.UUID `json:"trade_id"`
	FromFranchise pgtype.UUID `json:"from_franchise"`
	ToFranchise   pgtype.UUID `json:"to_franchise"`
	LeagueID      pgtype.UUID `json:"league_id"`
	PlayerID      pgtype.UUID `json:"player_id"`
	DraftPickID   pgtype.UUID `json:"draft_pick_id"`
}

type TradeParty struct {
	TradeID     pgtype.UUID        `json:"trade_id"`
	FranchiseID pgtype.UUID        `json:"franchise_id"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
}

type Transaction struct {
	ID          int64              `json:"id"`
	DynastyID   pgtype.UUID        `json:"dynasty_id"`
	LeagueID    pgtype.UUID        `json:"league_id"`
	FranchiseID pgtype.UUID        `json:"franchise_id"`
	Kind        string             `json:"kind"`
	PlayerID    pgtype.UUID        `json:"player_id"`
	Detail      json.RawMessage    `json:"detail"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DraftPickID pgtype.UUID        `json:"draft_pick_id"`
	TradeID     pgtype.UUID        `json:"trade_id"`
}

type User struct {
	ID                pgtype.UUID        `json:"id"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	SessionsValidFrom pgtype.Timestamptz `json:"sessions_valid_from"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Waiver struct {
	LeagueID pgtype.UUID        `json:"league_id"`
	PlayerID pgtype.UUID        `json:"player_id"`
	ClearsAt pgtype.Timestamptz `json:"clears_at"`
}

type WaiverClaim struct {
	ID           pgtype.UUID        `json:"id"`
	LeagueID     pgtype.UUID        `json:"league_id"`
	FranchiseID  pgtype.UUID        `json:"franchise_id"`
	PlayerID     pgtype.UUID        `json:"player_id"`
	DropPlayerID pgtype.UUID        `json:"drop_player_id"`
	Bid          int32              `json:"bid"`
	Status       string             `json:"status"`
	Reason       string             `json:"reason"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
}
