// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlayerExternalID = `-- name: AddPlayerExternalID :exec
insert into player_external_ids (provider, provider_id, player_id)
values ($1, $2, $3)
on conflict (provider, provider_id) do nothing
`

type AddPlayerExternalIDParams struct {
	Provider   string      `json:"provider"`
	ProviderID string      `json:"provider_id"`
	PlayerID   pgtype.UUID `json:"player_id"`
}

// Gives a player another feed id, when a second feed turns out to be
// describing someone we already have.
func (q *Queries) AddPlayerExternalID(ctx context.Context, arg AddPlayerExternalIDParams) error {
	_, err := q.db.Exec(ctx, addPlayerExternalID, arg.Provider, arg.ProviderID, arg.PlayerID)
	return err
}

const countPlayers = `-- name: CountPlayers :one
select count(*)
from players p
left join roster_entries r on r.player_id = p.id
where ($1::text = '' or p.competition = $1)
  and ($2::text = '' or p.status = $2)
  and ($3::text = '' or p.full_name ilike '%' || $3 || '%')
  and ($4::uuid is null or (
        r.player_id is null
        and p.competition = (select l.competition from leagues l where l.id = $4)))
  and ($5::uuid is null or (
        r.player_id is null
        and p.competition in (select l.competition from draft_leagues dl
                              join leagues l on l.id = dl.league_id
                              where dl.draft_id = $5)))
`

type CountPlayersParams struct {
	Competition string      `json:"competition"`
	Status      string      `json:"status"`
	Search      string      `json:"search"`
	AvailableIn pgtype.UUID `json:"available_in"`
	DraftID     pgtype.UUID `json:"draft_id"`
}

func (q *Queries) CountPlayers(ctx context.Context, arg CountPlayersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayers,
		arg.Competition,
		arg.Status,
		arg.Search,
		arg.AvailableIn,
		arg.DraftID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlayersByCompetition = `-- name: CountPlayersByCompetition :many
select competition, count(*) as players from players group by competition
`

type CountPlayersByCompetitionRow struct {
	Competition string `json:"competition"`
	Players     int64  `json:"players"`
}

func (q *Queries) CountPlayersByCompetition(ctx context.Context) ([]CountPlayersByCompetitionRow, error) {
	rows, err := q.db.Query(ctx, countPlayersByCompetition)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountPlayersByCompetitionRow{}
	for rows.Next() {
		var i CountPlayersByCompetitionRow
		if err := rows.Scan(&i.Competition, &i.Players); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePlayer = `-- name: DeletePlayer :exec
delete from players where id = $1
`

func (q *Queries) DeletePlayer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePlayer, id)
	return err
}

const deletePlayersOutsidePool = `-- name: DeletePlayersOutsidePool :execrows
delete from players p
where p.competition = $1
  and ((cardinality($2::text[]) > 0 and cardinality(p.positions) > 0 and not p.positions && $2::text[])
    or ($3::boolean and p.pro_team_id in (
          select t.id from pro_teams t
          where t.competition = $1 and t.provider_id <> all($4::text[]))))
  and not exists (select 1 from roster_entries r where r.player_id = p.id)
  and not exists (select 1 from transactions x where x.player_id = p.id)
  and not exists (select 1 from draft_picks k where k.player_id = p.id)
  and not exists (select 1 from trade_items i where i.player_id = p.id)
`

type DeletePlayersOutsidePoolParams struct {
	Competition     string   `json:"competition"`
	Positions       []string `json:"positions"`
	ListedTeamsOnly bool     `json:"listed_teams_only"`
	TeamIds         []string `json:"team_ids"`
}

// Removes players a narrowed competition no longer covers: at none of its
// positions, or on a team it does not list. A player with any fantasy
// history stays, and is marked inactive by the roster sync like anyone
// else who has left.
func (q *Queries) DeletePlayersOutsidePool(ctx context.Context, arg DeletePlayersOutsidePoolParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlayersOutsidePool,
		arg.Competition,
		arg.Positions,
		arg.ListedTeamsOnly,
		arg.TeamIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUnlistedTeams = `-- name: DeleteUnlistedTeams :execrows
delete from pro_teams where competition = $1 and provider_id <> all($2::text[])
`

type DeleteUnlistedTeamsParams struct {
	Competition string   `json:"competition"`
	TeamIds     []string `json:"team_ids"`
}

func (q *Queries) DeleteUnlistedTeams(ctx context.Context, arg DeleteUnlistedTeamsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnlistedTeams, arg.Competition, arg.TeamIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const detachUnlistedTeams = `-- name: DetachUnlistedTeams :exec
with gone as (
  select t.id from pro_teams t where t.competition = $1 and t.provider_id <> all($2::text[])
), released as (
  update players set pro_team_id = null where pro_team_id in (select id from gone)
)
update games set
  home_team_id = case when home_team_id in (select id from gone) then null else home_team_id end,
  away_team_id = case when away_team_id in (select id from gone) then null else away_team_id end
where home_team_id in (select id from gone) or away_team_id in (select id from gone)
`

type DetachUnlistedTeamsParams struct {
	Competition string   `json:"competition"`
	TeamIds     []string `json:"team_ids"`
}

// Before DeleteUnlistedTeams: nothing may still point at a team being removed.
func (q *Queries) DetachUnlistedTeams(ctx context.Context, arg DetachUnlistedTeamsParams) error {
	_, err := q.db.Exec(ctx, detachUnlistedTeams, arg.Competition, arg.TeamIds)
	return err
}

const findPlayerByExternalID = `-- name: FindPlayerByExternalID :one
select player_id from player_external_ids
where provider = $1 and provider_id = $2
`

type FindPlayerByExternalIDParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) FindPlayerByExternalID(ctx context.Context, arg FindPlayerByExternalIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findPlayerByExternalID, arg.Provider, arg.ProviderID)
	var player_id pgtype.UUID
	err := row.Scan(&player_id)
	return player_id, err
}

const getLeagueByCompetition = `-- name: GetLeagueByCompetition :one
select id, dynasty_id, competition, name, settings, last_draft_at from leagues where dynasty_id = $1 and competition = $2
`

type GetLeagueByCompetitionParams struct {
	DynastyID   pgtype.UUID `json:"dynasty_id"`
	Competition string      `json:"competition"`
}

func (q *Queries) GetLeagueByCompetition(ctx context.Context, arg GetLeagueByCompetitionParams) (League, error) {
	row := q.db.QueryRow(ctx, getLeagueByCompetition, arg.DynastyID, arg.Competition)
	var i League
	err := row.Scan(
		&i.ID,
		&i.DynastyID,
		&i.Competition,
		&i.Name,
		&i.Settings,
		&i.LastDraftAt,
	)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
select id, competition, status, eligible_since, full_name, positions, birth_date, pro_team_id, class, note, headshot_url, updated_at, career_checked_at from players where id = $1
`

func (q *Queries) GetPlayer(ctx context.Context, id pgtype.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayer, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Competition,
		&i.Status,
		&i.EligibleSince,
		&i.FullName,
		&i.Positions,
		&i.BirthDate,
		&i.ProTeamID,
		&i.Class,
		&i.Note,
		&i.HeadshotUrl,
		&i.UpdatedAt,
		&i.CareerCheckedAt,
	)
	return i, err
}

const getPlayerExternalID = `-- name: GetPlayerExternalID :one
select provider_id from player_external_ids
where player_id = $1 and provider = $2
`

type GetPlayerExternalIDParams struct {
	PlayerID pgtype.UUID `json:"player_id"`
	Provider string      `json:"provider"`
}

// The player's id in one feed's id space, if that feed knows him.
func (q *Queries) GetPlayerExternalID(ctx context.Context, arg GetPlayerExternalIDParams) (string, error) {
	row := q.db.QueryRow(ctx, getPlayerExternalID, arg.PlayerID, arg.Provider)
	var provider_id string
	err := row.Scan(&provider_id)
	return provider_id, err
}

const getPlayerProfile = `-- name: GetPlayerProfile :one
select p.id, p.competition, p.status, p.full_name, p.positions, p.birth_date,
       p.class, p.note, p.headshot_url,
       coalesce(t.abbrev, '')::text as team_abbrev,
       coalesce(t.name, '')::text as team_name,
       coalesce(f.name, '')::text as owner_name,
       coalesce(f.slug, '')::text as owner_slug
from players p
left join pro_teams t on t.id = p.pro_team_id
left join roster_entries re on re.player_id = p.id
left join franchises f on f.id = re.franchise_id
where p.id = $1
`

type GetPlayerProfileRow struct {
	ID          pgtype.UUID `json:"id"`
	Competition string      `json:"competition"`
	Status      string      `json:"status"`
	FullName    string      `json:"full_name"`
	Positions   []string    `json:"positions"`
	BirthDate   pgtype.Date `json:"birth_date"`
	Class       string      `json:"class"`
	Note        string      `json:"note"`
	HeadshotUrl string      `json:"headshot_url"`
	TeamAbbrev  string      `json:"team_abbrev"`
	TeamName    string      `json:"team_name"`
	OwnerName   string      `json:"owner_name"`
	OwnerSlug   string      `json:"owner_slug"`
}

// A player's identity and current ownership for inline draft research.
func (q *Queries) GetPlayerProfile(ctx context.Context, id pgtype.UUID) (GetPlayerProfileRow, error) {
	row := q.db.QueryRow(ctx, getPlayerProfile, id)
	var i GetPlayerProfileRow
	err := row.Scan(
		&i.ID,
		&i.Competition,
		&i.Status,
		&i.FullName,
		&i.Positions,
		&i.BirthDate,
		&i.Class,
		&i.Note,
		&i.HeadshotUrl,
		&i.TeamAbbrev,
		&i.TeamName,
		&i.OwnerName,
		&i.OwnerSlug,
	)
	return i, err
}

const insertManualPlayer = `-- name: InsertManualPlayer :one
insert into players (competition, status, full_name, positions, birth_date, note)
values ($1, $2, $3, $4, $5, $6)
returning id
`

type InsertManualPlayerParams struct {
	Competition string      `json:"competition"`
	Status      string      `json:"status"`
	FullName    string      `json:"full_name"`
	Positions   []string    `json:"positions"`
	BirthDate   pgtype.Date `json:"birth_date"`
	Note        string      `json:"note"`
}

func (q *Queries) InsertManualPlayer(ctx context.Context, arg InsertManualPlayerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertManualPlayer,
		arg.Competition,
		arg.Status,
		arg.FullName,
		arg.Positions,
		arg.BirthDate,
		arg.Note,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertPlayer = `-- name: InsertPlayer :one
with new_player as (
  insert into players (competition, status, full_name, positions, birth_date, pro_team_id, class, headshot_url)
  values ($3, 'active', $4, $5, $6, $7, $8, $9)
  returning id
)
insert into player_external_ids (provider, provider_id, player_id)
select $1, $2, id from new_player
returning player_id
`

type InsertPlayerParams struct {
	Provider    string      `json:"provider"`
	ProviderID  string      `json:"provider_id"`
	Competition string      `json:"competition"`
	FullName    string      `json:"full_name"`
	Positions   []string    `json:"positions"`
	BirthDate   pgtype.Date `json:"birth_date"`
	ProTeamID   pgtype.UUID `json:"pro_team_id"`
	Class       string      `json:"class"`
	HeadshotUrl string      `json:"headshot_url"`
}

func (q *Queries) InsertPlayer(ctx context.Context, arg InsertPlayerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertPlayer,
		arg.Provider,
		arg.ProviderID,
		arg.Competition,
		arg.FullName,
		arg.Positions,
		arg.BirthDate,
		arg.ProTeamID,
		arg.Class,
		arg.HeadshotUrl,
	)
	var player_id pgtype.UUID
	err := row.Scan(&player_id)
	return player_id, err
}

const insertProspect = `-- name: InsertProspect :one
with new_player as (
  insert into players (competition, status, full_name, positions, birth_date, note, headshot_url)
  values ($3, 'prospect', $4, $5, $6, $7, $8)
  returning id
)
insert into player_external_ids (provider, provider_id, player_id)
select $1, $2, id from new_player
returning player_id
`

type InsertProspectParams struct {
	Provider    string      `json:"provider"`
	ProviderID  string      `json:"provider_id"`
	Competition string      `json:"competition"`
	FullName    string      `json:"full_name"`
	Positions   []string    `json:"positions"`
	BirthDate   pgtype.Date `json:"birth_date"`
	Note        string      `json:"note"`
	HeadshotUrl string      `json:"headshot_url"`
}

func (q *Queries) InsertProspect(ctx context.Context, arg InsertProspectParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertProspect,
		arg.Provider,
		arg.ProviderID,
		arg.Competition,
		arg.FullName,
		arg.Positions,
		arg.BirthDate,
		arg.Note,
		arg.HeadshotUrl,
	)
	var player_id pgtype.UUID
	err := row.Scan(&player_id)
	return player_id, err
}

const keepEarliestEligibility = `-- name: KeepEarliestEligibility :exec
update players k set eligible_since = least(k.eligible_since, d.eligible_since)
from players d
where k.id = $1 and d.id = $2
`

type KeepEarliestEligibilityParams struct {
	KeepID      pgtype.UUID `json:"keep_id"`
	DuplicateID pgtype.UUID `json:"duplicate_id"`
}

func (q *Queries) KeepEarliestEligibility(ctx context.Context, arg KeepEarliestEligibilityParams) error {
	_, err := q.db.Exec(ctx, keepEarliestEligibility, arg.KeepID, arg.DuplicateID)
	return err
}

const listMergeSuggestions = `-- name: ListMergeSuggestions :many
select a.id as prospect_id, a.full_name, a.competition, a.note as prospect_note,
       b.id as player_id, b.status as player_status, b.class as player_class,
       coalesce(t.name, '')::text as player_team
from players a
join players b on b.competition = a.competition
              and lower(b.full_name) = lower(a.full_name)
              and b.status <> 'prospect'
left join pro_teams t on t.id = b.pro_team_id
where a.status = 'prospect'
  -- Written as a lookup per pair: joining the ids to each other first
  -- pairs every id with every other from its feed, millions of rows.
  and not exists (
    select 1 from player_external_ids xa
    where xa.player_id = a.id
      and xa.provider in (select xb.provider from player_external_ids xb where xb.player_id = b.id))
order by a.full_name
limit 200
`

type ListMergeSuggestionsRow struct {
	ProspectID   pgtype.UUID `json:"prospect_id"`
	FullName     string      `json:"full_name"`
	Competition  string      `json:"competition"`
	ProspectNote string      `json:"prospect_note"`
	PlayerID     pgtype.UUID `json:"player_id"`
	PlayerStatus string      `json:"player_status"`
	PlayerClass  string      `json:"player_class"`
	PlayerTeam   string      `json:"player_team"`
}

// A prospect and an arrived player with the same name in the same
// competition may be one person entered through two feeds. Two rows with
// ids from the same feed are known to be different people, so those pairs
// are left out.
func (q *Queries) ListMergeSuggestions(ctx context.Context) ([]ListMergeSuggestionsRow, error) {
	rows, err := q.db.Query(ctx, listMergeSuggestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMergeSuggestionsRow{}
	for rows.Next() {
		var i ListMergeSuggestionsRow
		if err := rows.Scan(
			&i.ProspectID,
			&i.FullName,
			&i.Competition,
			&i.ProspectNote,
			&i.PlayerID,
			&i.PlayerStatus,
			&i.PlayerClass,
			&i.PlayerTeam,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerHistory = `-- name: ListPlayerHistory :many
select g.id, g.day, coalesce(a.abbrev, '')::text as away_abbrev,
       coalesce(h.abbrev, '')::text as home_abbrev, sl.stats,
       coalesce((select sum(stat.value::numeric * rule.value::numeric)
                 from jsonb_each_text(sl.stats) stat
                 join lateral jsonb_each_text(l.settings->'scoring') rule on rule.key = stat.key), 0)::float8 as points
from stat_lines sl
join games g on g.id = sl.game_id
left join pro_teams a on a.id = g.away_team_id
left join pro_teams h on h.id = g.home_team_id
left join leagues l on l.competition = g.competition
where sl.player_id = $1 and g.status = 'final' and g.competition = $2
order by g.starts_at desc, g.id desc
limit 10
`

type ListPlayerHistoryParams struct {
	PlayerID    pgtype.UUID `json:"player_id"`
	Competition string      `json:"competition"`
}

type ListPlayerHistoryRow struct {
	ID         pgtype.UUID     `json:"id"`
	Day        pgtype.Date     `json:"day"`
	AwayAbbrev string          `json:"away_abbrev"`
	HomeAbbrev string          `json:"home_abbrev"`
	Stats      json.RawMessage `json:"stats"`
	Points     float64         `json:"points"`
}

// Last ten recorded finals in the player's current competition. Scoring
// is calculated with current league rules, just as on the game pages.
func (q *Queries) ListPlayerHistory(ctx context.Context, arg ListPlayerHistoryParams) ([]ListPlayerHistoryRow, error) {
	rows, err := q.db.Query(ctx, listPlayerHistory, arg.PlayerID, arg.Competition)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerHistoryRow{}
	for rows.Next() {
		var i ListPlayerHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Day,
			&i.AwayAbbrev,
			&i.HomeAbbrev,
			&i.Stats,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerRosterEntries = `-- name: ListPlayerRosterEntries :many
select re.league_id, re.franchise_id, re.player_id, re.list, re.acquired_via, re.acquired_at, re.reserved_at from roster_entries re where re.player_id = $1
`

func (q *Queries) ListPlayerRosterEntries(ctx context.Context, playerID pgtype.UUID) ([]RosterEntry, error) {
	rows, err := q.db.Query(ctx, listPlayerRosterEntries, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RosterEntry{}
	for rows.Next() {
		var i RosterEntry
		if err := rows.Scan(
			&i.LeagueID,
			&i.FranchiseID,
			&i.PlayerID,
			&i.List,
			&i.AcquiredVia,
			&i.AcquiredAt,
			&i.ReservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayers = `-- name: ListPlayers :many
select p.id, p.competition, p.status, p.full_name, p.positions, p.birth_date,
       p.class, p.note, p.headshot_url, p.eligible_since,
       coalesce(t.abbrev, '')::text as team_abbrev,
       coalesce(t.name, '')::text   as team_name,
       coalesce(f.name, '')::text   as owner_name,
       coalesce(f.slug, '')::text   as owner_slug,
       w.clears_at                  as waiver_until
from players p
left join pro_teams t      on t.id = p.pro_team_id
left join roster_entries r on r.player_id = p.id
left join franchises f     on f.id = r.franchise_id
left join waivers w        on w.player_id = p.id
where ($1::text = '' or p.competition = $1)
  and ($2::text = '' or p.status = $2)
  and ($3::text = '' or p.full_name ilike '%' || $3 || '%')
  and ($4::uuid is null or (
        r.player_id is null
        and p.competition = (select l.competition from leagues l where l.id = $4)))
  and ($5::uuid is null or (
        r.player_id is null
        and p.competition in (select l.competition from draft_leagues dl
                              join leagues l on l.id = dl.league_id
                              where dl.draft_id = $5)))
order by p.full_name, p.id
limit $7 offset $6
`

type ListPlayersParams struct {
	Competition string      `json:"competition"`
	Status      string      `json:"status"`
	Search      string      `json:"search"`
	AvailableIn pgtype.UUID `json:"available_in"`
	DraftID     pgtype.UUID `json:"draft_id"`
	PageOffset  int32       `json:"page_offset"`
	PageSize    int32       `json:"page_size"`
}

type ListPlayersRow struct {
	ID            pgtype.UUID        `json:"id"`
	Competition   string             `json:"competition"`
	Status        string             `json:"status"`
	FullName      string             `json:"full_name"`
	Positions     []string           `json:"positions"`
	BirthDate     pgtype.Date        `json:"birth_date"`
	Class         string             `json:"class"`
	Note          string             `json:"note"`
	HeadshotUrl   string             `json:"headshot_url"`
	EligibleSince pgtype.Timestamptz `json:"eligible_since"`
	TeamAbbrev    string             `json:"team_abbrev"`
	TeamName      string             `json:"team_name"`
	OwnerName     string             `json:"owner_name"`
	OwnerSlug     string             `json:"owner_slug"`
	WaiverUntil   pgtype.Timestamptz `json:"waiver_until"`
}

// available_in narrows to players a league could acquire: they play in its
// competition and are on nobody's roster there. draft_id does the same for
// every league a draft covers.
func (q *Queries) ListPlayers(ctx context.Context, arg ListPlayersParams) ([]ListPlayersRow, error) {
	rows, err := q.db.Query(ctx, listPlayers,
		arg.Competition,
		arg.Status,
		arg.Search,
		arg.AvailableIn,
		arg.DraftID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayersRow{}
	for rows.Next() {
		var i ListPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Competition,
			&i.Status,
			&i.FullName,
			&i.Positions,
			&i.BirthDate,
			&i.Class,
			&i.Note,
			&i.HeadshotUrl,
			&i.EligibleSince,
			&i.TeamAbbrev,
			&i.TeamName,
			&i.OwnerName,
			&i.OwnerSlug,
			&i.WaiverUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRosteredInactive = `-- name: ListRosteredInactive :many
select p.id as player_id, p.full_name, p.positions, p.competition, p.note,
       re.league_id, re.list, f.id as franchise_id, f.name as franchise_name, f.slug as franchise_slug
from roster_entries re
join players p on p.id = re.player_id
join franchises f on f.id = re.franchise_id
where f.dynasty_id = $1 and p.status = 'inactive'
order by p.full_name
`

type ListRosteredInactiveRow struct {
	PlayerID      pgtype.UUID `json:"player_id"`
	FullName      string      `json:"full_name"`
	Positions     []string    `json:"positions"`
	Competition   string      `json:"competition"`
	Note          string      `json:"note"`
	LeagueID      pgtype.UUID `json:"league_id"`
	List          string      `json:"list"`
	FranchiseID   pgtype.UUID `json:"franchise_id"`
	FranchiseName string      `json:"franchise_name"`
	FranchiseSlug string      `json:"franchise_slug"`
}

// Rostered players who have dropped out of their competition's feed: left
// college without turning pro, retired, released abroad.
func (q *Queries) ListRosteredInactive(ctx context.Context, dynastyID pgtype.UUID) ([]ListRosteredInactiveRow, error) {
	rows, err := q.db.Query(ctx, listRosteredInactive, dynastyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRosteredInactiveRow{}
	for rows.Next() {
		var i ListRosteredInactiveRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.FullName,
			&i.Positions,
			&i.Competition,
			&i.Note,
			&i.LeagueID,
			&i.List,
			&i.FranchiseID,
			&i.FranchiseName,
			&i.FranchiseSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMissingInactive = `-- name: MarkMissingInactive :execrows
update players set status = 'inactive', pro_team_id = null
where competition = $1 and status = 'active' and updated_at < $2
`

type MarkMissingInactiveParams struct {
	Competition string             `json:"competition"`
	SeenBefore  pgtype.Timestamptz `json:"seen_before"`
}

func (q *Queries) MarkMissingInactive(ctx context.Context, arg MarkMissingInactiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMissingInactive, arg.Competition, arg.SeenBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveExternalIDs = `-- name: MoveExternalIDs :exec
update player_external_ids set player_id = $1 where player_id = $2
`

type MoveExternalIDsParams struct {
	KeepID      pgtype.UUID `json:"keep_id"`
	DuplicateID pgtype.UUID `json:"duplicate_id"`
}

func (q *Queries) MoveExternalIDs(ctx context.Context, arg MoveExternalIDsParams) error {
	_, err := q.db.Exec(ctx, moveExternalIDs, arg.KeepID, arg.DuplicateID)
	return err
}

const movePlayerCompetition = `-- name: MovePlayerCompetition :exec
update players set competition = $1, status = 'prospect', eligible_since = now(), pro_team_id = null
where id = $2
`

type MovePlayerCompetitionParams struct {
	Competition string      `json:"competition"`
	ID          pgtype.UUID `json:"id"`
}

// Puts a player in another competition's pool by hand, as a prospect there.
func (q *Queries) MovePlayerCompetition(ctx context.Context, arg MovePlayerCompetitionParams) error {
	_, err := q.db.Exec(ctx, movePlayerCompetition, arg.Competition, arg.ID)
	return err
}

const moveRosterEntries = `-- name: MoveRosterEntries :exec
update roster_entries set player_id = $1 where player_id = $2
`

type MoveRosterEntriesParams struct {
	KeepID      pgtype.UUID `json:"keep_id"`
	DuplicateID pgtype.UUID `json:"duplicate_id"`
}

func (q *Queries) MoveRosterEntries(ctx context.Context, arg MoveRosterEntriesParams) error {
	_, err := q.db.Exec(ctx, moveRosterEntries, arg.KeepID, arg.DuplicateID)
	return err
}

const moveTransactions = `-- name: MoveTransactions :exec
update transactions set player_id = $1 where player_id = $2
`

type MoveTransactionsParams struct {
	KeepID      pgtype.UUID `json:"keep_id"`
	DuplicateID pgtype.UUID `json:"duplicate_id"`
}

func (q *Queries) MoveTransactions(ctx context.Context, arg MoveTransactionsParams) error {
	_, err := q.db.Exec(ctx, moveTransactions, arg.KeepID, arg.DuplicateID)
	return err
}

const updatePlayer = `-- name: UpdatePlayer :one
update players set
  eligible_since = case when competition <> $1 then now() else eligible_since end,
  competition    = $1,
  status         = 'active',
  full_name      = $2,
  positions      = $3,
  birth_date     = coalesce($4, birth_date),
  pro_team_id    = $5,
  class          = $6,
  headshot_url   = $7,
  updated_at     = now()
where players.id = $8
returning (select was.competition from players was where was.id = players.id)::text as previous_competition
`

type UpdatePlayerParams struct {
	Competition string      `json:"competition"`
	FullName    string      `json:"full_name"`
	Positions   []string    `json:"positions"`
	BirthDate   pgtype.Date `json:"birth_date"`
	ProTeamID   pgtype.UUID `json:"pro_team_id"`
	Class       string      `json:"class"`
	HeadshotUrl string      `json:"headshot_url"`
	ID          pgtype.UUID `json:"id"`
}

// Returns the competition the player was in before, so a move (a college
// player reaching the NBA) can be acted on.
func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (string, error) {
	row := q.db.QueryRow(ctx, updatePlayer,
		arg.Competition,
		arg.FullName,
		arg.Positions,
		arg.BirthDate,
		arg.ProTeamID,
		arg.Class,
		arg.HeadshotUrl,
		arg.ID,
	)
	var previous_competition string
	err := row.Scan(&previous_competition)
	return previous_competition, err
}

const updateProspect = `-- name: UpdateProspect :exec
update players set
  full_name    = $1,
  positions    = $2,
  birth_date   = coalesce($3, birth_date),
  note         = $4,
  headshot_url = $5,
  updated_at   = now()
where id = $6 and status = 'prospect'
`

type UpdateProspectParams struct {
	FullName    string      `json:"full_name"`
	Positions   []string    `json:"positions"`
	BirthDate   pgtype.Date `json:"birth_date"`
	Note        string      `json:"note"`
	HeadshotUrl string      `json:"headshot_url"`
	ID          pgtype.UUID `json:"id"`
}

// Only touches rows that are still prospects: a prospect feed must never
// overwrite a player who has since arrived.
func (q *Queries) UpdateProspect(ctx context.Context, arg UpdateProspectParams) error {
	_, err := q.db.Exec(ctx, updateProspect,
		arg.FullName,
		arg.Positions,
		arg.BirthDate,
		arg.Note,
		arg.HeadshotUrl,
		arg.ID,
	)
	return err
}

const upsertProTeam = `-- name: UpsertProTeam :one
insert into pro_teams (competition, provider_id, abbrev, name, logo_url)
values ($1, $2, $3, $4, $5)
on conflict (competition, provider_id) do update
  set abbrev = excluded.abbrev, name = excluded.name, logo_url = excluded.logo_url
returning id
`

type UpsertProTeamParams struct {
	Competition string `json:"competition"`
	ProviderID  string `json:"provider_id"`
	Abbrev      string `json:"abbrev"`
	Name        string `json:"name"`
	LogoUrl     string `json:"logo_url"`
}

func (q *Queries) UpsertProTeam(ctx context.Context, arg UpsertProTeamParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertProTeam,
		arg.Competition,
		arg.ProviderID,
		arg.Abbrev,
		arg.Name,
		arg.LogoUrl,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
