// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_profile.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlayerGameLog = `-- name: CountPlayerGameLog :one
select count(*) from stat_lines sl join games g on g.id = sl.game_id
where sl.player_id = $1 and g.status = 'final'
  and ($2::text = '' or g.competition = $2)
`

type CountPlayerGameLogParams struct {
	PlayerID    pgtype.UUID `json:"player_id"`
	Competition string      `json:"competition"`
}

func (q *Queries) CountPlayerGameLog(ctx context.Context, arg CountPlayerGameLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayerGameLog, arg.PlayerID, arg.Competition)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlayerTimeline = `-- name: CountPlayerTimeline :one
select count(*) from transactions where player_id = $1
`

func (q *Queries) CountPlayerTimeline(ctx context.Context, playerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayerTimeline, playerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listPlayerDraftRecord = `-- name: ListPlayerDraftRecord :many
select k.id, k.round, k.position, k.auto_picked, k.picked_at,
       d.id as draft_id, d.name as draft_name, d.year, d.kind,
       f.name as franchise_name, f.slug as franchise_slug, coalesce(l.competition, '')::text as competition
from draft_picks k join drafts d on d.id = k.draft_id
join franchises f on f.id = k.current_franchise_id
left join leagues l on l.id = k.league_id
where k.player_id = $1 order by k.picked_at desc, k.position
`

type ListPlayerDraftRecordRow struct {
	ID            pgtype.UUID        `json:"id"`
	Round         int32              `json:"round"`
	Position      int32              `json:"position"`
	AutoPicked    bool               `json:"auto_picked"`
	PickedAt      pgtype.Timestamptz `json:"picked_at"`
	DraftID       pgtype.UUID        `json:"draft_id"`
	DraftName     string             `json:"draft_name"`
	Year          int32              `json:"year"`
	Kind          string             `json:"kind"`
	FranchiseName string             `json:"franchise_name"`
	FranchiseSlug string             `json:"franchise_slug"`
	Competition   string             `json:"competition"`
}

func (q *Queries) ListPlayerDraftRecord(ctx context.Context, playerID pgtype.UUID) ([]ListPlayerDraftRecordRow, error) {
	rows, err := q.db.Query(ctx, listPlayerDraftRecord, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerDraftRecordRow{}
	for rows.Next() {
		var i ListPlayerDraftRecordRow
		if err := rows.Scan(
			&i.ID,
			&i.Round,
			&i.Position,
			&i.AutoPicked,
			&i.PickedAt,
			&i.DraftID,
			&i.DraftName,
			&i.Year,
			&i.Kind,
			&i.FranchiseName,
			&i.FranchiseSlug,
			&i.Competition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerGameLog = `-- name: ListPlayerGameLog :many
select g.id, g.competition, g.day, g.starts_at, sl.stats,
       coalesce(a.abbrev, '')::text as away_abbrev, coalesce(h.abbrev, '')::text as home_abbrev
from stat_lines sl join games g on g.id = sl.game_id
left join pro_teams a on a.id = g.away_team_id
left join pro_teams h on h.id = g.home_team_id
where sl.player_id = $1 and g.status = 'final'
  and ($2::text = '' or g.competition = $2)
order by g.starts_at desc, g.id desc limit $4 offset $3
`

type ListPlayerGameLogParams struct {
	PlayerID    pgtype.UUID `json:"player_id"`
	Competition string      `json:"competition"`
	PageOffset  int32       `json:"page_offset"`
	PageSize    int32       `json:"page_size"`
}

type ListPlayerGameLogRow struct {
	ID          pgtype.UUID        `json:"id"`
	Competition string             `json:"competition"`
	Day         pgtype.Date        `json:"day"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	Stats       json.RawMessage    `json:"stats"`
	AwayAbbrev  string             `json:"away_abbrev"`
	HomeAbbrev  string             `json:"home_abbrev"`
}

func (q *Queries) ListPlayerGameLog(ctx context.Context, arg ListPlayerGameLogParams) ([]ListPlayerGameLogRow, error) {
	rows, err := q.db.Query(ctx, listPlayerGameLog,
		arg.PlayerID,
		arg.Competition,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerGameLogRow{}
	for rows.Next() {
		var i ListPlayerGameLogRow
		if err := rows.Scan(
			&i.ID,
			&i.Competition,
			&i.Day,
			&i.StartsAt,
			&i.Stats,
			&i.AwayAbbrev,
			&i.HomeAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerOwnership = `-- name: ListPlayerOwnership :many
select r.league_id, l.competition, l.name as league_name,
       f.name as franchise_name, f.slug as franchise_slug, f.id as franchise_id,
       r.list, r.acquired_via, r.acquired_at, r.reserved_at,
       coalesce(case when r.list = 'main' then (select e.slot from lineup_entries e
         where e.league_id = r.league_id and e.franchise_id = r.franchise_id and e.player_id = r.player_id
           and e.effective_on = (select max(n.effective_on) from lineups n
             where n.league_id = r.league_id and n.franchise_id = r.franchise_id and n.effective_on <= $1::date)) end, '')::text as slot
from roster_entries r join leagues l on l.id = r.league_id
join franchises f on f.id = r.franchise_id
where r.player_id = $2 order by l.competition
`

type ListPlayerOwnershipParams struct {
	Day      pgtype.Date `json:"day"`
	PlayerID pgtype.UUID `json:"player_id"`
}

type ListPlayerOwnershipRow struct {
	LeagueID      pgtype.UUID        `json:"league_id"`
	Competition   string             `json:"competition"`
	LeagueName    string             `json:"league_name"`
	FranchiseName string             `json:"franchise_name"`
	FranchiseSlug string             `json:"franchise_slug"`
	FranchiseID   pgtype.UUID        `json:"franchise_id"`
	List          string             `json:"list"`
	AcquiredVia   string             `json:"acquired_via"`
	AcquiredAt    pgtype.Timestamptz `json:"acquired_at"`
	ReservedAt    pgtype.Timestamptz `json:"reserved_at"`
	Slot          string             `json:"slot"`
}

func (q *Queries) ListPlayerOwnership(ctx context.Context, arg ListPlayerOwnershipParams) ([]ListPlayerOwnershipRow, error) {
	rows, err := q.db.Query(ctx, listPlayerOwnership, arg.Day, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerOwnershipRow{}
	for rows.Next() {
		var i ListPlayerOwnershipRow
		if err := rows.Scan(
			&i.LeagueID,
			&i.Competition,
			&i.LeagueName,
			&i.FranchiseName,
			&i.FranchiseSlug,
			&i.FranchiseID,
			&i.List,
			&i.AcquiredVia,
			&i.AcquiredAt,
			&i.ReservedAt,
			&i.Slot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerTimeline = `-- name: ListPlayerTimeline :many
select x.id, x.kind, x.detail, x.created_at,
       coalesce(l.competition, '')::text as competition,
       coalesce(f.name, '')::text as franchise_name, coalesce(f.slug, '')::text as franchise_slug,
       x.trade_id, x.draft_pick_id, coalesce(d.id, null)::uuid as draft_id,
       coalesce(d.name, '')::text as draft_name, coalesce(k.round, 0)::int as pick_round,
       coalesce(k.position, 0)::int as pick_position
from transactions x
left join leagues l on l.id = x.league_id
left join franchises f on f.id = x.franchise_id
left join draft_picks k on k.id = x.draft_pick_id
left join drafts d on d.id = k.draft_id
where x.player_id = $1
order by x.id desc limit $3 offset $2
`

type ListPlayerTimelineParams struct {
	PlayerID   pgtype.UUID `json:"player_id"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

type ListPlayerTimelineRow struct {
	ID            int64              `json:"id"`
	Kind          string             `json:"kind"`
	Detail        json.RawMessage    `json:"detail"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Competition   string             `json:"competition"`
	FranchiseName string             `json:"franchise_name"`
	FranchiseSlug string             `json:"franchise_slug"`
	TradeID       pgtype.UUID        `json:"trade_id"`
	DraftPickID   pgtype.UUID        `json:"draft_pick_id"`
	DraftID       pgtype.UUID        `json:"draft_id"`
	DraftName     string             `json:"draft_name"`
	PickRound     int32              `json:"pick_round"`
	PickPosition  int32              `json:"pick_position"`
}

func (q *Queries) ListPlayerTimeline(ctx context.Context, arg ListPlayerTimelineParams) ([]ListPlayerTimelineRow, error) {
	rows, err := q.db.Query(ctx, listPlayerTimeline, arg.PlayerID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerTimelineRow{}
	for rows.Next() {
		var i ListPlayerTimelineRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Detail,
			&i.CreatedAt,
			&i.Competition,
			&i.FranchiseName,
			&i.FranchiseSlug,
			&i.TradeID,
			&i.DraftPickID,
			&i.DraftID,
			&i.DraftName,
			&i.PickRound,
			&i.PickPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerTradeRecord = `-- name: ListPlayerTradeRecord :many
select t.id, t.status, t.note, t.created_at, t.resolved_at,
       f.name as from_name, f.slug as from_slug, dest.name as to_name, dest.slug as to_slug,
       l.competition
from trade_items i join trades t on t.id = i.trade_id
join leagues l on l.id = i.league_id
join franchises f on f.id = i.from_franchise
join franchises dest on dest.id = i.to_franchise
where i.player_id = $1 and t.status in ('executed', 'reversed')
order by t.created_at desc
`

type ListPlayerTradeRecordRow struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	Note        string             `json:"note"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ResolvedAt  pgtype.Timestamptz `json:"resolved_at"`
	FromName    string             `json:"from_name"`
	FromSlug    string             `json:"from_slug"`
	ToName      string             `json:"to_name"`
	ToSlug      string             `json:"to_slug"`
	Competition string             `json:"competition"`
}

func (q *Queries) ListPlayerTradeRecord(ctx context.Context, playerID pgtype.UUID) ([]ListPlayerTradeRecordRow, error) {
	rows, err := q.db.Query(ctx, listPlayerTradeRecord, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerTradeRecordRow{}
	for rows.Next() {
		var i ListPlayerTradeRecordRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Note,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.FromName,
			&i.FromSlug,
			&i.ToName,
			&i.ToSlug,
			&i.Competition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerWaiverStatus = `-- name: ListPlayerWaiverStatus :many
select w.league_id, l.competition, w.clears_at
from waivers w join leagues l on l.id = w.league_id
where w.player_id = $1
`

type ListPlayerWaiverStatusRow struct {
	LeagueID    pgtype.UUID        `json:"league_id"`
	Competition string             `json:"competition"`
	ClearsAt    pgtype.Timestamptz `json:"clears_at"`
}

func (q *Queries) ListPlayerWaiverStatus(ctx context.Context, playerID pgtype.UUID) ([]ListPlayerWaiverStatusRow, error) {
	rows, err := q.db.Query(ctx, listPlayerWaiverStatus, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerWaiverStatusRow{}
	for rows.Next() {
		var i ListPlayerWaiverStatusRow
		if err := rows.Scan(&i.LeagueID, &i.Competition, &i.ClearsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
