// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ranking.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearRankingPlayers = `-- name: ClearRankingPlayers :exec
delete from ranking_players where ranking_id = $1
`

func (q *Queries) ClearRankingPlayers(ctx context.Context, rankingID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearRankingPlayers, rankingID)
	return err
}

const createRanking = `-- name: CreateRanking :one
insert into rankings (franchise_id, league_id, draft_id, name)
values ($1, $2, $3, $4)
returning id, franchise_id, league_id, draft_id, name, updated_at
`

type CreateRankingParams struct {
	FranchiseID pgtype.UUID `json:"franchise_id"`
	LeagueID    pgtype.UUID `json:"league_id"`
	DraftID     pgtype.UUID `json:"draft_id"`
	Name        string      `json:"name"`
}

func (q *Queries) CreateRanking(ctx context.Context, arg CreateRankingParams) (Ranking, error) {
	row := q.db.QueryRow(ctx, createRanking,
		arg.FranchiseID,
		arg.LeagueID,
		arg.DraftID,
		arg.Name,
	)
	var i Ranking
	err := row.Scan(
		&i.ID,
		&i.FranchiseID,
		&i.LeagueID,
		&i.DraftID,
		&i.Name,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRanking = `-- name: DeleteRanking :execrows
delete from rankings where id = $1 and franchise_id = $2
`

type DeleteRankingParams struct {
	ID          pgtype.UUID `json:"id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
}

func (q *Queries) DeleteRanking(ctx context.Context, arg DeleteRankingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRanking, arg.ID, arg.FranchiseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const draftCoversLeague = `-- name: DraftCoversLeague :one
select exists (select 1 from draft_leagues where draft_id = $1 and league_id = $2)
`

type DraftCoversLeagueParams struct {
	DraftID  pgtype.UUID `json:"draft_id"`
	LeagueID pgtype.UUID `json:"league_id"`
}

func (q *Queries) DraftCoversLeague(ctx context.Context, arg DraftCoversLeagueParams) (bool, error) {
	row := q.db.QueryRow(ctx, draftCoversLeague, arg.DraftID, arg.LeagueID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getRanking = `-- name: GetRanking :one
select id, franchise_id, league_id, draft_id, name, updated_at from rankings where id = $1 and franchise_id = $2
`

type GetRankingParams struct {
	ID          pgtype.UUID `json:"id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
}

func (q *Queries) GetRanking(ctx context.Context, arg GetRankingParams) (Ranking, error) {
	row := q.db.QueryRow(ctx, getRanking, arg.ID, arg.FranchiseID)
	var i Ranking
	err := row.Scan(
		&i.ID,
		&i.FranchiseID,
		&i.LeagueID,
		&i.DraftID,
		&i.Name,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRankingPlayer = `-- name: InsertRankingPlayer :execrows
insert into ranking_players (ranking_id, player_id, rank)
select $1, p.id, $2
from players p
join rankings r on r.id = $1
left join leagues l on l.id = r.league_id
where p.id = $3 and (
 p.competition = l.competition or (r.league_id is null and exists (
  select 1 from draft_leagues dl join leagues covered on covered.id = dl.league_id
  where dl.draft_id = r.draft_id and covered.competition = p.competition
 ))
)
`

type InsertRankingPlayerParams struct {
	RankingID pgtype.UUID `json:"ranking_id"`
	Rank      int32       `json:"rank"`
	PlayerID  pgtype.UUID `json:"player_id"`
}

// League boards cover one sport; combined startup boards cover their draft’s sports.
func (q *Queries) InsertRankingPlayer(ctx context.Context, arg InsertRankingPlayerParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRankingPlayer, arg.RankingID, arg.Rank, arg.PlayerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listRankingPlayers = `-- name: ListRankingPlayers :many
select rp.player_id, rp.rank, p.full_name, p.positions, p.competition, p.status, p.note, p.headshot_url,
       coalesce(t.abbrev, '')::text as team_abbrev,
       coalesce(f.name, '')::text   as owner_name
from ranking_players rp
join rankings r on r.id = rp.ranking_id
join players p on p.id = rp.player_id
left join pro_teams t on t.id = p.pro_team_id
left join roster_entries re on re.player_id = p.id and (re.league_id = r.league_id or (r.league_id is null and re.league_id in (select league_id from draft_leagues where draft_id = r.draft_id)))
left join franchises f on f.id = re.franchise_id
where rp.ranking_id = $1
order by rp.rank
`

type ListRankingPlayersRow struct {
	PlayerID    pgtype.UUID `json:"player_id"`
	Rank        int32       `json:"rank"`
	FullName    string      `json:"full_name"`
	Positions   []string    `json:"positions"`
	Competition string      `json:"competition"`
	Status      string      `json:"status"`
	Note        string      `json:"note"`
	HeadshotUrl string      `json:"headshot_url"`
	TeamAbbrev  string      `json:"team_abbrev"`
	OwnerName   string      `json:"owner_name"`
}

// The ranked players in order, with who holds each one in the ranking's league.
func (q *Queries) ListRankingPlayers(ctx context.Context, rankingID pgtype.UUID) ([]ListRankingPlayersRow, error) {
	rows, err := q.db.Query(ctx, listRankingPlayers, rankingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRankingPlayersRow{}
	for rows.Next() {
		var i ListRankingPlayersRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.Rank,
			&i.FullName,
			&i.Positions,
			&i.Competition,
			&i.Status,
			&i.Note,
			&i.HeadshotUrl,
			&i.TeamAbbrev,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRankings = `-- name: ListRankings :many
select r.id, r.league_id, r.draft_id, r.name, r.updated_at,
       coalesce(l.competition, '')::text as competition,
       coalesce(d.name, '')::text as draft_name,
       (select count(*) from ranking_players rp where rp.ranking_id = r.id) as players
from rankings r
left join leagues l on l.id = r.league_id
left join drafts d on d.id = r.draft_id
where r.franchise_id = $1
order by l.competition, r.name, r.id
`

type ListRankingsRow struct {
	ID          pgtype.UUID        `json:"id"`
	LeagueID    pgtype.UUID        `json:"league_id"`
	DraftID     pgtype.UUID        `json:"draft_id"`
	Name        string             `json:"name"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Competition string             `json:"competition"`
	DraftName   string             `json:"draft_name"`
	Players     int64              `json:"players"`
}

func (q *Queries) ListRankings(ctx context.Context, franchiseID pgtype.UUID) ([]ListRankingsRow, error) {
	rows, err := q.db.Query(ctx, listRankings, franchiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRankingsRow{}
	for rows.Next() {
		var i ListRankingsRow
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.DraftID,
			&i.Name,
			&i.UpdatedAt,
			&i.Competition,
			&i.DraftName,
			&i.Players,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRanking = `-- name: UpdateRanking :exec
update rankings set name = $1, draft_id = $2, updated_at = now() where id = $3
`

type UpdateRankingParams struct {
	Name    string      `json:"name"`
	DraftID pgtype.UUID `json:"draft_id"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRanking(ctx context.Context, arg UpdateRankingParams) error {
	_, err := q.db.Exec(ctx, updateRanking, arg.Name, arg.DraftID, arg.ID)
	return err
}
