// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: research.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const listResearchPlayers = `-- name: ListResearchPlayers :many
with latest as (
  select competition, max(year) as year from player_seasons
  where league = '' group by competition
), totals as (
  select ps.player_id, ps.competition, max(ps.label)::text as season,
         sum(ps.games)::integer as games,
         string_agg(distinct nullif(ps.team, ''), ' / ')::text as season_team
  from player_seasons ps
  join latest on latest.competition = ps.competition
  where ps.league = ''
    and (($4::text = '' and ps.year = latest.year) or ps.label = $4)
  group by ps.player_id, ps.competition
), stats as (
  select ps.player_id, ps.competition, stat.key, sum(stat.value::numeric)::float8 as value
  from player_seasons ps
  join latest on latest.competition = ps.competition
  cross join lateral jsonb_each_text(ps.stats) as stat(key, value)
  where ps.league = ''
    and (($4::text = '' and ps.year = latest.year) or ps.label = $4)
  group by ps.player_id, ps.competition, stat.key
), valued as (
  select stats.player_id, stats.competition, jsonb_object_agg(stats.key, stats.value) as stats,
         coalesce(sum(stats.value * (l.settings->'scoring'->>stats.key)::float8), 0)::float8 as points
  from stats left join leagues l on l.competition = stats.competition
  group by stats.player_id, stats.competition
), pool as (
  select p.id, p.competition, p.full_name, p.positions, p.status, p.headshot_url,
         coalesce(totals.season_team, t.abbrev, '')::text as team,
         coalesce(f.name, '')::text as owner_name, coalesce(f.slug, '')::text as owner_slug,
         coalesce(totals.season, '')::text as season,
         coalesce(totals.games, 0)::integer as games,
         coalesce(valued.stats, '{}'::jsonb) as stats,
         coalesce(valued.points, 0)::float8 as points,
         coalesce(valued.points / nullif(totals.games, 0), 0)::float8 as points_per_game
  from players p
  left join pro_teams t on t.id = p.pro_team_id
  left join roster_entries r on r.player_id = p.id
  left join franchises f on f.id = r.franchise_id
  left join totals on totals.player_id = p.id and totals.competition = p.competition
  left join valued on valued.player_id = p.id and valued.competition = p.competition
  where ($5::text = '' or p.competition = $5)
    and ($6::text = '' or p.status = $6)
    and ($7::text = '' or p.full_name ilike '%' || $7 || '%')
    and ($8::uuid is null or (
      r.player_id is null and p.competition = (select competition from leagues where id = $8)))
)
select pool.id, pool.competition, pool.full_name, pool.positions, pool.status, pool.headshot_url, pool.team, pool.owner_name, pool.owner_slug, pool.season, pool.games, pool.stats, pool.points, pool.points_per_game from pool
order by
  case when $1::text = 'name' then full_name end asc,
  case when $1 = 'points' and season <> '' then points
       when $1 = 'points_per_game' and games > 0 then points_per_game
       when $1 = 'games' and season <> '' then games::float8
       else (stats ->> $1::text)::float8 end desc nulls last,
  full_name, id
limit $3 offset $2
`

type ListResearchPlayersParams struct {
	Sort        string      `json:"sort"`
	PageOffset  int32       `json:"page_offset"`
	PageSize    int32       `json:"page_size"`
	Season      string      `json:"season"`
	Competition string      `json:"competition"`
	Status      string      `json:"status"`
	Search      string      `json:"search"`
	AvailableIn pgtype.UUID `json:"available_in"`
}

type ListResearchPlayersRow struct {
	ID            pgtype.UUID     `json:"id"`
	Competition   string          `json:"competition"`
	FullName      string          `json:"full_name"`
	Positions     []string        `json:"positions"`
	Status        string          `json:"status"`
	HeadshotUrl   string          `json:"headshot_url"`
	Team          string          `json:"team"`
	OwnerName     string          `json:"owner_name"`
	OwnerSlug     string          `json:"owner_slug"`
	Season        string          `json:"season"`
	Games         int32           `json:"games"`
	Stats         json.RawMessage `json:"stats"`
	Points        float64         `json:"points"`
	PointsPerGame float64         `json:"points_per_game"`
}

// Latest means the newest imported season in each competition, shared by
// all players. Aggregate team splits before applying current scoring rules.
func (q *Queries) ListResearchPlayers(ctx context.Context, arg ListResearchPlayersParams) ([]ListResearchPlayersRow, error) {
	rows, err := q.db.Query(ctx, listResearchPlayers,
		arg.Sort,
		arg.PageOffset,
		arg.PageSize,
		arg.Season,
		arg.Competition,
		arg.Status,
		arg.Search,
		arg.AvailableIn,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResearchPlayersRow{}
	for rows.Next() {
		var i ListResearchPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Competition,
			&i.FullName,
			&i.Positions,
			&i.Status,
			&i.HeadshotUrl,
			&i.Team,
			&i.OwnerName,
			&i.OwnerSlug,
			&i.Season,
			&i.Games,
			&i.Stats,
			&i.Points,
			&i.PointsPerGame,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResearchSeasons = `-- name: ListResearchSeasons :many
select distinct ps.label, ps.year
from player_seasons ps
where ps.league = '' and ($1::text = '' or ps.competition = $1)
order by ps.year desc, ps.label desc
`

type ListResearchSeasonsRow struct {
	Label string `json:"label"`
	Year  int32  `json:"year"`
}

func (q *Queries) ListResearchSeasons(ctx context.Context, competition string) ([]ListResearchSeasonsRow, error) {
	rows, err := q.db.Query(ctx, listResearchSeasons, competition)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResearchSeasonsRow{}
	for rows.Next() {
		var i ListResearchSeasonsRow
		if err := rows.Scan(&i.Label, &i.Year); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
