// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roster.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRosterEntry = `-- name: DeleteRosterEntry :execrows
delete from roster_entries
where league_id = $1 and franchise_id = $2 and player_id = $3
`

type DeleteRosterEntryParams struct {
	LeagueID    pgtype.UUID `json:"league_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
	PlayerID    pgtype.UUID `json:"player_id"`
}

func (q *Queries) DeleteRosterEntry(ctx context.Context, arg DeleteRosterEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRosterEntry, arg.LeagueID, arg.FranchiseID, arg.PlayerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRosterEntry = `-- name: GetRosterEntry :one
select league_id, franchise_id, player_id, list, acquired_via, acquired_at, reserved_at from roster_entries where league_id = $1 and player_id = $2
`

type GetRosterEntryParams struct {
	LeagueID pgtype.UUID `json:"league_id"`
	PlayerID pgtype.UUID `json:"player_id"`
}

func (q *Queries) GetRosterEntry(ctx context.Context, arg GetRosterEntryParams) (RosterEntry, error) {
	row := q.db.QueryRow(ctx, getRosterEntry, arg.LeagueID, arg.PlayerID)
	var i RosterEntry
	err := row.Scan(
		&i.LeagueID,
		&i.FranchiseID,
		&i.PlayerID,
		&i.List,
		&i.AcquiredVia,
		&i.AcquiredAt,
		&i.ReservedAt,
	)
	return i, err
}

const insertRosterEntry = `-- name: InsertRosterEntry :exec
insert into roster_entries (league_id, franchise_id, player_id, list, acquired_via, reserved_at)
values ($1, $2, $3, $4, $5, $6)
`

type InsertRosterEntryParams struct {
	LeagueID    pgtype.UUID        `json:"league_id"`
	FranchiseID pgtype.UUID        `json:"franchise_id"`
	PlayerID    pgtype.UUID        `json:"player_id"`
	List        string             `json:"list"`
	AcquiredVia string             `json:"acquired_via"`
	ReservedAt  pgtype.Timestamptz `json:"reserved_at"`
}

func (q *Queries) InsertRosterEntry(ctx context.Context, arg InsertRosterEntryParams) error {
	_, err := q.db.Exec(ctx, insertRosterEntry,
		arg.LeagueID,
		arg.FranchiseID,
		arg.PlayerID,
		arg.List,
		arg.AcquiredVia,
		arg.ReservedAt,
	)
	return err
}

const insertTransaction = `-- name: InsertTransaction :exec
insert into transactions (dynasty_id, league_id, franchise_id, kind, player_id, draft_pick_id, trade_id, detail)
values ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertTransactionParams struct {
	DynastyID   pgtype.UUID     `json:"dynasty_id"`
	LeagueID    pgtype.UUID     `json:"league_id"`
	FranchiseID pgtype.UUID     `json:"franchise_id"`
	Kind        string          `json:"kind"`
	PlayerID    pgtype.UUID     `json:"player_id"`
	DraftPickID pgtype.UUID     `json:"draft_pick_id"`
	TradeID     pgtype.UUID     `json:"trade_id"`
	Detail      json.RawMessage `json:"detail"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.Exec(ctx, insertTransaction,
		arg.DynastyID,
		arg.LeagueID,
		arg.FranchiseID,
		arg.Kind,
		arg.PlayerID,
		arg.DraftPickID,
		arg.TradeID,
		arg.Detail,
	)
	return err
}

const listActivity = `-- name: ListActivity :many
select x.id, x.kind, x.detail, x.created_at,
       coalesce(l.competition, '')::text as competition,
       coalesce(f.name, '')::text        as franchise_name,
       coalesce(f.slug, '')::text        as franchise_slug,
       coalesce(p.full_name, '')::text   as player_name,
       coalesce(d.name, '')::text        as draft_name,
       coalesce(k.round, 0)::int         as pick_round
from transactions x
left join leagues l     on l.id = x.league_id
left join franchises f  on f.id = x.franchise_id
left join players p     on p.id = x.player_id
left join draft_picks k on k.id = x.draft_pick_id
left join drafts d      on d.id = k.draft_id
where x.dynasty_id = $1
order by x.id desc
limit $2
`

type ListActivityParams struct {
	DynastyID pgtype.UUID `json:"dynasty_id"`
	PageSize  int32       `json:"page_size"`
}

type ListActivityRow struct {
	ID            int64              `json:"id"`
	Kind          string             `json:"kind"`
	Detail        json.RawMessage    `json:"detail"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Competition   string             `json:"competition"`
	FranchiseName string             `json:"franchise_name"`
	FranchiseSlug string             `json:"franchise_slug"`
	PlayerName    string             `json:"player_name"`
	DraftName     string             `json:"draft_name"`
	PickRound     int32              `json:"pick_round"`
}

func (q *Queries) ListActivity(ctx context.Context, arg ListActivityParams) ([]ListActivityRow, error) {
	rows, err := q.db.Query(ctx, listActivity, arg.DynastyID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityRow{}
	for rows.Next() {
		var i ListActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Detail,
			&i.CreatedAt,
			&i.Competition,
			&i.FranchiseName,
			&i.FranchiseSlug,
			&i.PlayerName,
			&i.DraftName,
			&i.PickRound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFranchiseRoster = `-- name: ListFranchiseRoster :many
select r.league_id, r.list, r.acquired_via, r.acquired_at, r.reserved_at,
       p.id as player_id, p.full_name, p.positions, p.status, p.class, p.note, p.birth_date, p.headshot_url,
       coalesce(t.abbrev, '')::text as team_abbrev
from roster_entries r
join players p on p.id = r.player_id
left join pro_teams t on t.id = p.pro_team_id
where r.franchise_id = $1
order by p.full_name
`

type ListFranchiseRosterRow struct {
	LeagueID    pgtype.UUID        `json:"league_id"`
	List        string             `json:"list"`
	AcquiredVia string             `json:"acquired_via"`
	AcquiredAt  pgtype.Timestamptz `json:"acquired_at"`
	ReservedAt  pgtype.Timestamptz `json:"reserved_at"`
	PlayerID    pgtype.UUID        `json:"player_id"`
	FullName    string             `json:"full_name"`
	Positions   []string           `json:"positions"`
	Status      string             `json:"status"`
	Class       string             `json:"class"`
	Note        string             `json:"note"`
	BirthDate   pgtype.Date        `json:"birth_date"`
	HeadshotUrl string             `json:"headshot_url"`
	TeamAbbrev  string             `json:"team_abbrev"`
}

// Every player a franchise holds, across all its leagues, for display.
func (q *Queries) ListFranchiseRoster(ctx context.Context, franchiseID pgtype.UUID) ([]ListFranchiseRosterRow, error) {
	rows, err := q.db.Query(ctx, listFranchiseRoster, franchiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFranchiseRosterRow{}
	for rows.Next() {
		var i ListFranchiseRosterRow
		if err := rows.Scan(
			&i.LeagueID,
			&i.List,
			&i.AcquiredVia,
			&i.AcquiredAt,
			&i.ReservedAt,
			&i.PlayerID,
			&i.FullName,
			&i.Positions,
			&i.Status,
			&i.Class,
			&i.Note,
			&i.BirthDate,
			&i.HeadshotUrl,
			&i.TeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRosterEntries = `-- name: ListRosterEntries :many
select r.player_id, r.list, p.status
from roster_entries r
join players p on p.id = r.player_id
where r.league_id = $1 and r.franchise_id = $2
`

type ListRosterEntriesParams struct {
	LeagueID    pgtype.UUID `json:"league_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
}

type ListRosterEntriesRow struct {
	PlayerID pgtype.UUID `json:"player_id"`
	List     string      `json:"list"`
	Status   string      `json:"status"`
}

// The facts roster limits depend on.
func (q *Queries) ListRosterEntries(ctx context.Context, arg ListRosterEntriesParams) ([]ListRosterEntriesRow, error) {
	rows, err := q.db.Query(ctx, listRosterEntries, arg.LeagueID, arg.FranchiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRosterEntriesRow{}
	for rows.Next() {
		var i ListRosterEntriesRow
		if err := rows.Scan(&i.PlayerID, &i.List, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFranchiseRoster = `-- name: LockFranchiseRoster :exec
select pg_advisory_xact_lock(hashtextextended($1::text || $2::text, 0))
`

type LockFranchiseRosterParams struct {
	LeagueID    string `json:"league_id"`
	FranchiseID string `json:"franchise_id"`
}

// Serializes roster changes for one franchise in one league until the
// surrounding transaction ends.
func (q *Queries) LockFranchiseRoster(ctx context.Context, arg LockFranchiseRosterParams) error {
	_, err := q.db.Exec(ctx, lockFranchiseRoster, arg.LeagueID, arg.FranchiseID)
	return err
}

const setRosterList = `-- name: SetRosterList :exec
update roster_entries set list = $1, reserved_at = $2
where league_id = $3 and franchise_id = $4 and player_id = $5
`

type SetRosterListParams struct {
	List        string             `json:"list"`
	ReservedAt  pgtype.Timestamptz `json:"reserved_at"`
	LeagueID    pgtype.UUID        `json:"league_id"`
	FranchiseID pgtype.UUID        `json:"franchise_id"`
	PlayerID    pgtype.UUID        `json:"player_id"`
}

func (q *Queries) SetRosterList(ctx context.Context, arg SetRosterListParams) error {
	_, err := q.db.Exec(ctx, setRosterList,
		arg.List,
		arg.ReservedAt,
		arg.LeagueID,
		arg.FranchiseID,
		arg.PlayerID,
	)
	return err
}
