// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scoring.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeSeason = `-- name: CompleteSeason :exec
update seasons set status = 'complete', champion_franchise_id = $1 where id = $2
`

type CompleteSeasonParams struct {
	ChampionFranchiseID pgtype.UUID `json:"champion_franchise_id"`
	ID                  pgtype.UUID `json:"id"`
}

func (q *Queries) CompleteSeason(ctx context.Context, arg CompleteSeasonParams) error {
	_, err := q.db.Exec(ctx, completeSeason, arg.ChampionFranchiseID, arg.ID)
	return err
}

const copyLineupEntries = `-- name: CopyLineupEntries :exec
insert into lineup_entries (league_id, franchise_id, effective_on, slot, slot_index, player_id, counts_from)
select e.league_id, e.franchise_id, $1, e.slot, e.slot_index, e.player_id, e.counts_from
from lineup_entries e
where e.league_id = $2 and e.franchise_id = $3 and e.effective_on = $4
`

type CopyLineupEntriesParams struct {
	ToDay       pgtype.Date `json:"to_day"`
	LeagueID    pgtype.UUID `json:"league_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
	FromDay     pgtype.Date `json:"from_day"`
}

func (q *Queries) CopyLineupEntries(ctx context.Context, arg CopyLineupEntriesParams) error {
	_, err := q.db.Exec(ctx, copyLineupEntries,
		arg.ToDay,
		arg.LeagueID,
		arg.FranchiseID,
		arg.FromDay,
	)
	return err
}

const createSeason = `-- name: CreateSeason :one

insert into seasons (league_id, year, starts_on, ends_on)
values ($1, $2, $3, $4)
returning id, league_id, year, starts_on, ends_on, status, champion_franchise_id
`

type CreateSeasonParams struct {
	LeagueID pgtype.UUID `json:"league_id"`
	Year     int32       `json:"year"`
	StartsOn pgtype.Date `json:"starts_on"`
	EndsOn   pgtype.Date `json:"ends_on"`
}

// ---- seasons ----
func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, createSeason,
		arg.LeagueID,
		arg.Year,
		arg.StartsOn,
		arg.EndsOn,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.Year,
		&i.StartsOn,
		&i.EndsOn,
		&i.Status,
		&i.ChampionFranchiseID,
	)
	return i, err
}

const deleteLineups = `-- name: DeleteLineups :exec
delete from lineups
where league_id = $1 and franchise_id = $2 and effective_on between $3 and $4
`

type DeleteLineupsParams struct {
	LeagueID    pgtype.UUID `json:"league_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
	FromDay     pgtype.Date `json:"from_day"`
	ToDay       pgtype.Date `json:"to_day"`
}

// Removes the lineups that take effect within a span of days.
func (q *Queries) DeleteLineups(ctx context.Context, arg DeleteLineupsParams) error {
	_, err := q.db.Exec(ctx, deleteLineups,
		arg.LeagueID,
		arg.FranchiseID,
		arg.FromDay,
		arg.ToDay,
	)
	return err
}

const deletePeriodsFrom = `-- name: DeletePeriodsFrom :exec
delete from periods where season_id = $1 and starts_on >= $2
`

type DeletePeriodsFromParams struct {
	SeasonID pgtype.UUID `json:"season_id"`
	FromDay  pgtype.Date `json:"from_day"`
}

// Removes the periods that start on or after a day, with their matchups.
func (q *Queries) DeletePeriodsFrom(ctx context.Context, arg DeletePeriodsFromParams) error {
	_, err := q.db.Exec(ctx, deletePeriodsFrom, arg.SeasonID, arg.FromDay)
	return err
}

const getGame = `-- name: GetGame :one
select id, competition, provider_id, day, starts_at, status, home_team_id, away_team_id, stats_synced_at, home_score, away_score, detail from games where id = $1
`

func (q *Queries) GetGame(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Competition,
		&i.ProviderID,
		&i.Day,
		&i.StartsAt,
		&i.Status,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.StatsSyncedAt,
		&i.HomeScore,
		&i.AwayScore,
		&i.Detail,
	)
	return i, err
}

const getGameSummary = `-- name: GetGameSummary :one
select g.id, g.competition, g.day, g.starts_at, g.status, g.detail, g.home_score, g.away_score,
       coalesce(h.abbrev, '')::text   as home_abbrev,
       coalesce(h.name, '')::text     as home_name,
       coalesce(h.logo_url, '')::text as home_logo,
       coalesce(a.abbrev, '')::text   as away_abbrev,
       coalesce(a.name, '')::text     as away_name,
       coalesce(a.logo_url, '')::text as away_logo
from games g
left join pro_teams h on h.id = g.home_team_id
left join pro_teams a on a.id = g.away_team_id
where g.id = $1
`

type GetGameSummaryRow struct {
	ID          pgtype.UUID        `json:"id"`
	Competition string             `json:"competition"`
	Day         pgtype.Date        `json:"day"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	Status      string             `json:"status"`
	Detail      string             `json:"detail"`
	HomeScore   int32              `json:"home_score"`
	AwayScore   int32              `json:"away_score"`
	HomeAbbrev  string             `json:"home_abbrev"`
	HomeName    string             `json:"home_name"`
	HomeLogo    string             `json:"home_logo"`
	AwayAbbrev  string             `json:"away_abbrev"`
	AwayName    string             `json:"away_name"`
	AwayLogo    string             `json:"away_logo"`
}

func (q *Queries) GetGameSummary(ctx context.Context, id pgtype.UUID) (GetGameSummaryRow, error) {
	row := q.db.QueryRow(ctx, getGameSummary, id)
	var i GetGameSummaryRow
	err := row.Scan(
		&i.ID,
		&i.Competition,
		&i.Day,
		&i.StartsAt,
		&i.Status,
		&i.Detail,
		&i.HomeScore,
		&i.AwayScore,
		&i.HomeAbbrev,
		&i.HomeName,
		&i.HomeLogo,
		&i.AwayAbbrev,
		&i.AwayName,
		&i.AwayLogo,
	)
	return i, err
}

const getMatchup = `-- name: GetMatchup :one
select id, period_id, home_franchise_id, away_franchise_id from matchups where id = $1
`

func (q *Queries) GetMatchup(ctx context.Context, id pgtype.UUID) (Matchup, error) {
	row := q.db.QueryRow(ctx, getMatchup, id)
	var i Matchup
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.HomeFranchiseID,
		&i.AwayFranchiseID,
	)
	return i, err
}

const getPeriod = `-- name: GetPeriod :one
select id, season_id, seq, starts_on, ends_on, is_playoff from periods where id = $1
`

func (q *Queries) GetPeriod(ctx context.Context, id pgtype.UUID) (Period, error) {
	row := q.db.QueryRow(ctx, getPeriod, id)
	var i Period
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Seq,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsPlayoff,
	)
	return i, err
}

const getSeason = `-- name: GetSeason :one
select id, league_id, year, starts_on, ends_on, status, champion_franchise_id from seasons where id = $1
`

func (q *Queries) GetSeason(ctx context.Context, id pgtype.UUID) (Season, error) {
	row := q.db.QueryRow(ctx, getSeason, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.Year,
		&i.StartsOn,
		&i.EndsOn,
		&i.Status,
		&i.ChampionFranchiseID,
	)
	return i, err
}

const insertLineup = `-- name: InsertLineup :exec
insert into lineups (league_id, franchise_id, effective_on) values ($1, $2, $3)
on conflict do nothing
`

type InsertLineupParams struct {
	LeagueID    pgtype.UUID `json:"league_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
	EffectiveOn pgtype.Date `json:"effective_on"`
}

func (q *Queries) InsertLineup(ctx context.Context, arg InsertLineupParams) error {
	_, err := q.db.Exec(ctx, insertLineup, arg.LeagueID, arg.FranchiseID, arg.EffectiveOn)
	return err
}

const insertLineupEntry = `-- name: InsertLineupEntry :exec
insert into lineup_entries (league_id, franchise_id, effective_on, slot, slot_index, player_id, counts_from)
values ($1, $2, $3, $4, $5, $6, $7)
`

type InsertLineupEntryParams struct {
	LeagueID    pgtype.UUID `json:"league_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
	EffectiveOn pgtype.Date `json:"effective_on"`
	Slot        string      `json:"slot"`
	SlotIndex   int32       `json:"slot_index"`
	PlayerID    pgtype.UUID `json:"player_id"`
	CountsFrom  pgtype.Date `json:"counts_from"`
}

func (q *Queries) InsertLineupEntry(ctx context.Context, arg InsertLineupEntryParams) error {
	_, err := q.db.Exec(ctx, insertLineupEntry,
		arg.LeagueID,
		arg.FranchiseID,
		arg.EffectiveOn,
		arg.Slot,
		arg.SlotIndex,
		arg.PlayerID,
		arg.CountsFrom,
	)
	return err
}

const insertMatchup = `-- name: InsertMatchup :exec
insert into matchups (period_id, home_franchise_id, away_franchise_id)
values ($1, $2, $3)
`

type InsertMatchupParams struct {
	PeriodID        pgtype.UUID `json:"period_id"`
	HomeFranchiseID pgtype.UUID `json:"home_franchise_id"`
	AwayFranchiseID pgtype.UUID `json:"away_franchise_id"`
}

func (q *Queries) InsertMatchup(ctx context.Context, arg InsertMatchupParams) error {
	_, err := q.db.Exec(ctx, insertMatchup, arg.PeriodID, arg.HomeFranchiseID, arg.AwayFranchiseID)
	return err
}

const insertPeriod = `-- name: InsertPeriod :one
insert into periods (season_id, seq, starts_on, ends_on, is_playoff)
values ($1, $2, $3, $4, $5)
returning id, season_id, seq, starts_on, ends_on, is_playoff
`

type InsertPeriodParams struct {
	SeasonID  pgtype.UUID `json:"season_id"`
	Seq       int32       `json:"seq"`
	StartsOn  pgtype.Date `json:"starts_on"`
	EndsOn    pgtype.Date `json:"ends_on"`
	IsPlayoff bool        `json:"is_playoff"`
}

func (q *Queries) InsertPeriod(ctx context.Context, arg InsertPeriodParams) (Period, error) {
	row := q.db.QueryRow(ctx, insertPeriod,
		arg.SeasonID,
		arg.Seq,
		arg.StartsOn,
		arg.EndsOn,
		arg.IsPlayoff,
	)
	var i Period
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Seq,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsPlayoff,
	)
	return i, err
}

const insertPeriodScore = `-- name: InsertPeriodScore :exec
insert into period_scores (period_id, franchise_id, points) values ($1, $2, $3)
on conflict do nothing
`

type InsertPeriodScoreParams struct {
	PeriodID    pgtype.UUID `json:"period_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
	Points      float64     `json:"points"`
}

func (q *Queries) InsertPeriodScore(ctx context.Context, arg InsertPeriodScoreParams) error {
	_, err := q.db.Exec(ctx, insertPeriodScore, arg.PeriodID, arg.FranchiseID, arg.Points)
	return err
}

const latestSeason = `-- name: LatestSeason :one
select id, league_id, year, starts_on, ends_on, status, champion_franchise_id from seasons where league_id = $1 order by year desc limit 1
`

func (q *Queries) LatestSeason(ctx context.Context, leagueID pgtype.UUID) (Season, error) {
	row := q.db.QueryRow(ctx, latestSeason, leagueID)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.Year,
		&i.StartsOn,
		&i.EndsOn,
		&i.Status,
		&i.ChampionFranchiseID,
	)
	return i, err
}

const lineupInForce = `-- name: LineupInForce :one

select max(effective_on)::date as effective_on from lineups
where league_id = $1 and franchise_id = $2 and effective_on <= $3
`

type LineupInForceParams struct {
	LeagueID    pgtype.UUID `json:"league_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
	Day         pgtype.Date `json:"day"`
}

// ---- lineups ----
// The day of the lineup that applies on a given day, if any has been set.
func (q *Queries) LineupInForce(ctx context.Context, arg LineupInForceParams) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, lineupInForce, arg.LeagueID, arg.FranchiseID, arg.Day)
	var effective_on pgtype.Date
	err := row.Scan(&effective_on)
	return effective_on, err
}

const listActiveSeasons = `-- name: ListActiveSeasons :many
select id, league_id, year, starts_on, ends_on, status, champion_franchise_id from seasons where status = 'active'
`

func (q *Queries) ListActiveSeasons(ctx context.Context) ([]Season, error) {
	rows, err := q.db.Query(ctx, listActiveSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Season{}
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.Year,
			&i.StartsOn,
			&i.EndsOn,
			&i.Status,
			&i.ChampionFranchiseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameLines = `-- name: ListGameLines :many
select p.id as player_id, p.full_name, p.positions, p.headshot_url,
       coalesce(p.pro_team_id = g.home_team_id, false)::boolean as at_home,
       sl.stats,
       coalesce(sl.points, 0)::float8 as points,
       coalesce(f.name, '')::text as owner_name,
       coalesce(f.slug, '')::text as owner_slug
from stat_lines sl
join games g on g.id = sl.game_id
join players p on p.id = sl.player_id
left join leagues l on l.competition = g.competition
left join roster_entries re on re.league_id = l.id and re.player_id = p.id
left join franchises f on f.id = re.franchise_id
where sl.game_id = $1
order by points desc, p.full_name
`

type ListGameLinesRow struct {
	PlayerID    pgtype.UUID     `json:"player_id"`
	FullName    string          `json:"full_name"`
	Positions   []string        `json:"positions"`
	HeadshotUrl string          `json:"headshot_url"`
	AtHome      bool            `json:"at_home"`
	Stats       json.RawMessage `json:"stats"`
	Points      float64         `json:"points"`
	OwnerName   string          `json:"owner_name"`
	OwnerSlug   string          `json:"owner_slug"`
}

// Every player's line in a game, with the fantasy points it is worth under
// the league that plays this sport and the franchise that has him, if any.
func (q *Queries) ListGameLines(ctx context.Context, gameID pgtype.UUID) ([]ListGameLinesRow, error) {
	rows, err := q.db.Query(ctx, listGameLines, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameLinesRow{}
	for rows.Next() {
		var i ListGameLinesRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.FullName,
			&i.Positions,
			&i.HeadshotUrl,
			&i.AtHome,
			&i.Stats,
			&i.Points,
			&i.OwnerName,
			&i.OwnerSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesInPlay = `-- name: ListGamesInPlay :many
select id, competition, provider_id, day, starts_at, status, home_team_id, away_team_id, stats_synced_at, home_score, away_score, detail from games
where competition = $1
  and (status = 'live'
       or (status = 'scheduled' and starts_at between now() - interval '8 hours' and now() + interval '2 minutes'))
order by starts_at
`

// Games that are live, or should have started: the ones worth polling.
func (q *Queries) ListGamesInPlay(ctx context.Context, competition string) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesInPlay, competition)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Competition,
			&i.ProviderID,
			&i.Day,
			&i.StartsAt,
			&i.Status,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.StatsSyncedAt,
			&i.HomeScore,
			&i.AwayScore,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesNeedingStats = `-- name: ListGamesNeedingStats :many
select id, competition, provider_id, day, starts_at, status, home_team_id, away_team_id, stats_synced_at, home_score, away_score, detail from games
where competition = $1
  and starts_at > now() - interval '4 days'
  and (status = 'live'
       or (status = 'final' and (stats_synced_at is null
           or (stats_synced_at < starts_at + interval '20 hours' and now() > starts_at + interval '20 hours'))))
order by starts_at
`

// Games to fetch a box score for: every live game, every finished game not
// yet fetched, and each finished game once more the next day, when stat
// corrections have been made.
func (q *Queries) ListGamesNeedingStats(ctx context.Context, competition string) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesNeedingStats, competition)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Competition,
			&i.ProviderID,
			&i.Day,
			&i.StartsAt,
			&i.Status,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.StatsSyncedAt,
			&i.HomeScore,
			&i.AwayScore,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesOnDay = `-- name: ListGamesOnDay :many

select g.id, g.competition, g.day, g.starts_at, g.status, g.detail, g.home_score, g.away_score,
       coalesce(h.abbrev, '')::text   as home_abbrev,
       coalesce(h.name, '')::text     as home_name,
       coalesce(h.logo_url, '')::text as home_logo,
       coalesce(a.abbrev, '')::text   as away_abbrev,
       coalesce(a.name, '')::text     as away_name,
       coalesce(a.logo_url, '')::text as away_logo
from games g
left join pro_teams h on h.id = g.home_team_id
left join pro_teams a on a.id = g.away_team_id
where g.competition = $1 and g.day = $2
order by g.starts_at, g.id
`

type ListGamesOnDayParams struct {
	Competition string      `json:"competition"`
	Day         pgtype.Date `json:"day"`
}

type ListGamesOnDayRow struct {
	ID          pgtype.UUID        `json:"id"`
	Competition string             `json:"competition"`
	Day         pgtype.Date        `json:"day"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	Status      string             `json:"status"`
	Detail      string             `json:"detail"`
	HomeScore   int32              `json:"home_score"`
	AwayScore   int32              `json:"away_score"`
	HomeAbbrev  string             `json:"home_abbrev"`
	HomeName    string             `json:"home_name"`
	HomeLogo    string             `json:"home_logo"`
	AwayAbbrev  string             `json:"away_abbrev"`
	AwayName    string             `json:"away_name"`
	AwayLogo    string             `json:"away_logo"`
}

// ---- scoreboards and game pages ----
func (q *Queries) ListGamesOnDay(ctx context.Context, arg ListGamesOnDayParams) ([]ListGamesOnDayRow, error) {
	rows, err := q.db.Query(ctx, listGamesOnDay, arg.Competition, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGamesOnDayRow{}
	for rows.Next() {
		var i ListGamesOnDayRow
		if err := rows.Scan(
			&i.ID,
			&i.Competition,
			&i.Day,
			&i.StartsAt,
			&i.Status,
			&i.Detail,
			&i.HomeScore,
			&i.AwayScore,
			&i.HomeAbbrev,
			&i.HomeName,
			&i.HomeLogo,
			&i.AwayAbbrev,
			&i.AwayName,
			&i.AwayLogo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLineupEntries = `-- name: ListLineupEntries :many
select slot, slot_index, player_id, counts_from from lineup_entries
where league_id = $1 and franchise_id = $2 and effective_on = $3
order by slot, slot_index
`

type ListLineupEntriesParams struct {
	LeagueID    pgtype.UUID `json:"league_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
	EffectiveOn pgtype.Date `json:"effective_on"`
}

type ListLineupEntriesRow struct {
	Slot       string      `json:"slot"`
	SlotIndex  int32       `json:"slot_index"`
	PlayerID   pgtype.UUID `json:"player_id"`
	CountsFrom pgtype.Date `json:"counts_from"`
}

func (q *Queries) ListLineupEntries(ctx context.Context, arg ListLineupEntriesParams) ([]ListLineupEntriesRow, error) {
	rows, err := q.db.Query(ctx, listLineupEntries, arg.LeagueID, arg.FranchiseID, arg.EffectiveOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLineupEntriesRow{}
	for rows.Next() {
		var i ListLineupEntriesRow
		if err := rows.Scan(
			&i.Slot,
			&i.SlotIndex,
			&i.PlayerID,
			&i.CountsFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLineupPoints = `-- name: ListLineupPoints :many

with days as (
  select generate_series($2::date, $3::date, interval '1 day')::date as day
), in_force as (
  select f.id as franchise_id, d.day,
         (select max(n.effective_on) from lineups n
          where n.league_id = $4 and n.franchise_id = f.id and n.effective_on <= d.day) as effective_on
  from franchises f
  cross join days d
  where f.dynasty_id = (select dynasty_id from leagues where id = $4)
), started as (
  select i.franchise_id, e.player_id, g.id as game_id, g.day, sl.stats, l.settings,
         coalesce((select (def.rule->>'games_per_week')::int
                   from jsonb_array_elements(l.settings->'lineup'->'slots') as def(rule)
                   where def.rule->>'name' = e.slot), 0) as games_per_week,
         row_number() over (partition by i.franchise_id, e.player_id, (g.day - $2::date) / 7
                            order by g.starts_at, g.id) as nth,
         coalesce((l.settings->'lineup'->>'pitcher_starts_per_week')::int, 0) as starts_allowed,
         -- A start, for the cap: he started the game, and if he is a reliever
         -- he went more than an inning, so an opener does not use one up.
         (coalesce((sl.stats->>'pit_gs')::numeric, 0) >= 1
          and (not ('RP' = any(pl.positions)) or coalesce((sl.stats->>'pit_ip')::numeric, 0) > 1)) as is_start,
         sum(case when coalesce((sl.stats->>'pit_gs')::numeric, 0) >= 1
                   and (not ('RP' = any(pl.positions)) or coalesce((sl.stats->>'pit_ip')::numeric, 0) > 1)
                  then 1 else 0 end)
           over (partition by i.franchise_id, (g.day - $2::date) / 7
                 order by g.starts_at, g.id, e.player_id) as starts_so_far
  from in_force i
  join lineup_entries e on e.league_id = $4 and e.franchise_id = i.franchise_id and e.effective_on = i.effective_on
  join players pl on pl.id = e.player_id
  join leagues l on l.id = $4
  join games g on g.competition = l.competition and g.day = i.day
  join stat_lines sl on sl.game_id = g.id and sl.player_id = e.player_id
  where (e.counts_from is null or g.day >= e.counts_from)
    and (l.competition <> 'cbb'
      or jsonb_array_length(coalesce(nullif(l.settings->'lineup'->'conferences', 'null'::jsonb), '["8","23","7","2","4","44","3","21"]'::jsonb)) = 0
      or coalesce(
        (select ps.conference from player_seasons ps
         join pro_teams team on team.competition = ps.competition and team.abbrev = ps.team
         where ps.player_id = sl.player_id and ps.competition = 'cbb' and ps.league = ''
           and ps.year = extract(year from g.day)::int + case when extract(month from g.day) >= 7 then 1 else 0 end
           and team.id in (g.home_team_id, g.away_team_id) and ps.conference <> '' limit 1),
        (select team.conference from players p join pro_teams team on team.id = p.pro_team_id where p.id = sl.player_id), '')
         in (select jsonb_array_elements_text(coalesce(nullif(l.settings->'lineup'->'conferences', 'null'::jsonb), '["8","23","7","2","4","44","3","21"]'::jsonb))))
)
select st.franchise_id, st.player_id, p.full_name, p.headshot_url, coalesce(n.nickname, '')::text as nickname,
       count(distinct st.game_id) as games,
       sum(s.value::numeric * r.value::numeric)::float8 as points
from started st
join players p on p.id = st.player_id
left join player_nicknames n on n.franchise_id = st.franchise_id and n.player_id = st.player_id
cross join lateral jsonb_each_text(st.stats) s
join lateral jsonb_each_text(st.settings->'scoring') r on r.key = s.key
where st.day >= $1::date
  and (st.games_per_week = 0 or st.nth <= st.games_per_week)
  and (st.starts_allowed = 0 or not st.is_start or st.starts_so_far <= st.starts_allowed)
group by st.franchise_id, st.player_id, p.full_name, p.headshot_url, n.nickname
order by points desc
`

type ListLineupPointsParams struct {
	FromDay   pgtype.Date `json:"from_day"`
	WeekStart pgtype.Date `json:"week_start"`
	ToDay     pgtype.Date `json:"to_day"`
	LeagueID  pgtype.UUID `json:"league_id"`
}

type ListLineupPointsRow struct {
	FranchiseID pgtype.UUID `json:"franchise_id"`
	PlayerID    pgtype.UUID `json:"player_id"`
	FullName    string      `json:"full_name"`
	HeadshotUrl string      `json:"headshot_url"`
	Nickname    string      `json:"nickname"`
	Games       int64       `json:"games"`
	Points      float64     `json:"points"`
}

// ---- points ----
// Fantasy points for a league over a span of days, by franchise and player:
// each day's stat lines for whoever was in the lineup in force that day,
// weighted by the league's scoring rules. A slot may count only some of a
// player's games each week (games_per_week): those are his first so many on
// or after the day his manager picked. A league may also cap a team's
// pitcher starts for the week (pitcher_starts_per_week): starts beyond it,
// in the order they were played, score nothing. Weeks are counted from
// week_start, the first day of the week from_day falls in, so a span that
// begins mid-week still knows which games came earlier.
func (q *Queries) ListLineupPoints(ctx context.Context, arg ListLineupPointsParams) ([]ListLineupPointsRow, error) {
	rows, err := q.db.Query(ctx, listLineupPoints,
		arg.FromDay,
		arg.WeekStart,
		arg.ToDay,
		arg.LeagueID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLineupPointsRow{}
	for rows.Next() {
		var i ListLineupPointsRow
		if err := rows.Scan(
			&i.FranchiseID,
			&i.PlayerID,
			&i.FullName,
			&i.HeadshotUrl,
			&i.Nickname,
			&i.Games,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriodScores = `-- name: ListPeriodScores :many

select ps.period_id, ps.franchise_id, ps.points from period_scores ps
join periods p on p.id = ps.period_id
where p.season_id = $1
`

// ---- settled periods ----
// What each franchise scored in the season's settled periods.
func (q *Queries) ListPeriodScores(ctx context.Context, seasonID pgtype.UUID) ([]PeriodScore, error) {
	rows, err := q.db.Query(ctx, listPeriodScores, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PeriodScore{}
	for rows.Next() {
		var i PeriodScore
		if err := rows.Scan(&i.PeriodID, &i.FranchiseID, &i.Points); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriods = `-- name: ListPeriods :many

select id, season_id, seq, starts_on, ends_on, is_playoff from periods where season_id = $1 order by seq
`

// ---- head-to-head ----
func (q *Queries) ListPeriods(ctx context.Context, seasonID pgtype.UUID) ([]Period, error) {
	rows, err := q.db.Query(ctx, listPeriods, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Period{}
	for rows.Next() {
		var i Period
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.Seq,
			&i.StartsOn,
			&i.EndsOn,
			&i.IsPlayoff,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProTeamIDs = `-- name: ListProTeamIDs :many

select provider_id, id from pro_teams where competition = $1
`

type ListProTeamIDsRow struct {
	ProviderID string      `json:"provider_id"`
	ID         pgtype.UUID `json:"id"`
}

// ---- games and stat lines ----
func (q *Queries) ListProTeamIDs(ctx context.Context, competition string) ([]ListProTeamIDsRow, error) {
	rows, err := q.db.Query(ctx, listProTeamIDs, competition)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProTeamIDsRow{}
	for rows.Next() {
		var i ListProTeamIDsRow
		if err := rows.Scan(&i.ProviderID, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRosterGames = `-- name: ListRosterGames :many
select p.id as player_id, p.full_name, p.positions, p.headshot_url,
       coalesce(n.nickname, '')::text as nickname,
       coalesce(t.abbrev, '')::text as team_abbrev, coalesce(t.conference, '')::text as conference,
       g.id as game_id, g.day as game_day, g.starts_at, coalesce(g.status, '')::text as game_status,
       coalesce(case when g.home_team_id = p.pro_team_id then away.abbrev else home.abbrev end, '')::text as opponent,
       coalesce(g.home_team_id = p.pro_team_id, false)::boolean as at_home,
       coalesce((select sl.points from stat_lines sl
                 where sl.game_id = g.id and sl.player_id = p.id), 0)::float8 as points
from roster_entries re
join players p on p.id = re.player_id
join leagues l on l.id = re.league_id
left join pro_teams t on t.id = p.pro_team_id
left join games g on g.competition = l.competition
                 and g.day between $1 and $2
                 and p.pro_team_id in (g.home_team_id, g.away_team_id)
left join pro_teams home on home.id = g.home_team_id
left join pro_teams away on away.id = g.away_team_id
left join player_nicknames n on n.franchise_id = re.franchise_id and n.player_id = p.id
where re.league_id = $3 and re.franchise_id = $4 and re.list = 'main'
order by p.full_name, p.id, g.starts_at
`

type ListRosterGamesParams struct {
	FromDay     pgtype.Date `json:"from_day"`
	ToDay       pgtype.Date `json:"to_day"`
	LeagueID    pgtype.UUID `json:"league_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
}

type ListRosterGamesRow struct {
	PlayerID    pgtype.UUID        `json:"player_id"`
	FullName    string             `json:"full_name"`
	Positions   []string           `json:"positions"`
	HeadshotUrl string             `json:"headshot_url"`
	Nickname    string             `json:"nickname"`
	TeamAbbrev  string             `json:"team_abbrev"`
	Conference  string             `json:"conference"`
	GameID      pgtype.UUID        `json:"game_id"`
	GameDay     pgtype.Date        `json:"game_day"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	GameStatus  string             `json:"game_status"`
	Opponent    string             `json:"opponent"`
	AtHome      bool               `json:"at_home"`
	Points      float64            `json:"points"`
}

// A franchise's main roster in one league with each player's games in a
// span of days and the fantasy points he scored in each. A player with no
// game in the span appears once, with no game.
func (q *Queries) ListRosterGames(ctx context.Context, arg ListRosterGamesParams) ([]ListRosterGamesRow, error) {
	rows, err := q.db.Query(ctx, listRosterGames,
		arg.FromDay,
		arg.ToDay,
		arg.LeagueID,
		arg.FranchiseID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRosterGamesRow{}
	for rows.Next() {
		var i ListRosterGamesRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.FullName,
			&i.Positions,
			&i.HeadshotUrl,
			&i.Nickname,
			&i.TeamAbbrev,
			&i.Conference,
			&i.GameID,
			&i.GameDay,
			&i.StartsAt,
			&i.GameStatus,
			&i.Opponent,
			&i.AtHome,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonMatchups = `-- name: ListSeasonMatchups :many
select m.id, m.period_id, m.home_franchise_id, m.away_franchise_id, p.seq, p.is_playoff from matchups m
join periods p on p.id = m.period_id
where p.season_id = $1
order by p.seq, m.id
`

type ListSeasonMatchupsRow struct {
	ID              pgtype.UUID `json:"id"`
	PeriodID        pgtype.UUID `json:"period_id"`
	HomeFranchiseID pgtype.UUID `json:"home_franchise_id"`
	AwayFranchiseID pgtype.UUID `json:"away_franchise_id"`
	Seq             int32       `json:"seq"`
	IsPlayoff       bool        `json:"is_playoff"`
}

func (q *Queries) ListSeasonMatchups(ctx context.Context, seasonID pgtype.UUID) ([]ListSeasonMatchupsRow, error) {
	rows, err := q.db.Query(ctx, listSeasonMatchups, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeasonMatchupsRow{}
	for rows.Next() {
		var i ListSeasonMatchupsRow
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.HomeFranchiseID,
			&i.AwayFranchiseID,
			&i.Seq,
			&i.IsPlayoff,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasons = `-- name: ListSeasons :many
select s.id, s.league_id, s.year, s.starts_on, s.ends_on, s.status, s.champion_franchise_id from seasons s
join leagues l on l.id = s.league_id
where l.dynasty_id = $1
order by s.year desc
`

func (q *Queries) ListSeasons(ctx context.Context, dynastyID pgtype.UUID) ([]Season, error) {
	rows, err := q.db.Query(ctx, listSeasons, dynastyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Season{}
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.Year,
			&i.StartsOn,
			&i.EndsOn,
			&i.Status,
			&i.ChampionFranchiseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeekStarts = `-- name: ListWeekStarts :many
select pl.id as player_id, pl.full_name, g.day, g.starts_at,
       coalesce((sl.stats->>'pit_ip')::numeric, 0)::float8 as innings
from generate_series($1::date, $2::date, interval '1 day') as d(day)
join lateral (
  select max(n.effective_on) as effective_on from lineups n
  where n.league_id = $3 and n.franchise_id = $4 and n.effective_on <= d.day::date
) in_force on true
join lineup_entries e on e.league_id = $3 and e.franchise_id = $4 and e.effective_on = in_force.effective_on
join players pl on pl.id = e.player_id
join leagues l on l.id = $3
join games g on g.competition = l.competition and g.day = d.day::date
join stat_lines sl on sl.game_id = g.id and sl.player_id = e.player_id
where coalesce((sl.stats->>'pit_gs')::numeric, 0) >= 1
  and (not ('RP' = any(pl.positions)) or coalesce((sl.stats->>'pit_ip')::numeric, 0) > 1)
order by g.starts_at, g.id, e.player_id
`

type ListWeekStartsParams struct {
	WeekStart   pgtype.Date `json:"week_start"`
	WeekEnd     pgtype.Date `json:"week_end"`
	LeagueID    pgtype.UUID `json:"league_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
}

type ListWeekStartsRow struct {
	PlayerID pgtype.UUID        `json:"player_id"`
	FullName string             `json:"full_name"`
	Day      pgtype.Date        `json:"day"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	Innings  float64            `json:"innings"`
}

// The pitcher starts one franchise's starters have made in a week, in the
// order they were played. See ListLineupPoints for what counts as one.
func (q *Queries) ListWeekStarts(ctx context.Context, arg ListWeekStartsParams) ([]ListWeekStartsRow, error) {
	rows, err := q.db.Query(ctx, listWeekStarts,
		arg.WeekStart,
		arg.WeekEnd,
		arg.LeagueID,
		arg.FranchiseID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWeekStartsRow{}
	for rows.Next() {
		var i ListWeekStartsRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.FullName,
			&i.Day,
			&i.StartsAt,
			&i.Innings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPeriod = `-- name: LockPeriod :exec
select pg_advisory_xact_lock(hashtextextended(($1::uuid)::text, 0))
`

// Held while a period is settled, and taken by whatever would unsettle it.
func (q *Queries) LockPeriod(ctx context.Context, periodID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockPeriod, periodID)
	return err
}

const markGameStatsSynced = `-- name: MarkGameStatsSynced :exec
update games set stats_synced_at = now() where id = $1
`

func (q *Queries) MarkGameStatsSynced(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markGameStatsSynced, id)
	return err
}

const moveLineupEntries = `-- name: MoveLineupEntries :exec
update lineup_entries set player_id = $1 where player_id = $2
`

type MoveLineupEntriesParams struct {
	KeepID      pgtype.UUID `json:"keep_id"`
	DuplicateID pgtype.UUID `json:"duplicate_id"`
}

func (q *Queries) MoveLineupEntries(ctx context.Context, arg MoveLineupEntriesParams) error {
	_, err := q.db.Exec(ctx, moveLineupEntries, arg.KeepID, arg.DuplicateID)
	return err
}

const moveStatLines = `-- name: MoveStatLines :exec

update stat_lines sl set player_id = $1
where sl.player_id = $2
  and not exists (select 1 from stat_lines k where k.game_id = sl.game_id and k.player_id = $1)
`

type MoveStatLinesParams struct {
	KeepID      pgtype.UUID `json:"keep_id"`
	DuplicateID pgtype.UUID `json:"duplicate_id"`
}

// ---- merging players ----
// Keeps the surviving player's own line where both have one for a game.
func (q *Queries) MoveStatLines(ctx context.Context, arg MoveStatLinesParams) error {
	_, err := q.db.Exec(ctx, moveStatLines, arg.KeepID, arg.DuplicateID)
	return err
}

const playerHasStartedGame = `-- name: PlayerHasStartedGame :one
select exists (
  select 1 from games g
  join players p on p.pro_team_id in (g.home_team_id, g.away_team_id)
  where p.id = $1 and g.competition = p.competition and g.day = $2 and g.starts_at <= now()
)
`

type PlayerHasStartedGameParams struct {
	PlayerID pgtype.UUID `json:"player_id"`
	Day      pgtype.Date `json:"day"`
}

// Whether the player's real team has a game on the day that has started.
func (q *Queries) PlayerHasStartedGame(ctx context.Context, arg PlayerHasStartedGameParams) (bool, error) {
	row := q.db.QueryRow(ctx, playerHasStartedGame, arg.PlayerID, arg.Day)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeFromLineups = `-- name: RemoveFromLineups :exec
delete from lineup_entries
where league_id = $1 and franchise_id = $2 and player_id = $3 and effective_on >= $4
`

type RemoveFromLineupsParams struct {
	LeagueID    pgtype.UUID `json:"league_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
	PlayerID    pgtype.UUID `json:"player_id"`
	FromDay     pgtype.Date `json:"from_day"`
}

// Takes a player out of every lineup that takes effect on or after a day.
func (q *Queries) RemoveFromLineups(ctx context.Context, arg RemoveFromLineupsParams) error {
	_, err := q.db.Exec(ctx, removeFromLineups,
		arg.LeagueID,
		arg.FranchiseID,
		arg.PlayerID,
		arg.FromDay,
	)
	return err
}

const reopenSeason = `-- name: ReopenSeason :exec
update seasons set status = 'active', champion_franchise_id = null where id = $1
`

func (q *Queries) ReopenSeason(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, reopenSeason, id)
	return err
}

const setSeasonDates = `-- name: SetSeasonDates :exec
update seasons set starts_on = $1, ends_on = $2 where id = $3
`

type SetSeasonDatesParams struct {
	StartsOn pgtype.Date `json:"starts_on"`
	EndsOn   pgtype.Date `json:"ends_on"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) SetSeasonDates(ctx context.Context, arg SetSeasonDatesParams) error {
	_, err := q.db.Exec(ctx, setSeasonDates, arg.StartsOn, arg.EndsOn, arg.ID)
	return err
}

const upsertGame = `-- name: UpsertGame :exec
insert into games (competition, provider_id, day, starts_at, status, home_team_id, away_team_id, home_score, away_score, detail)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
on conflict (competition, provider_id) do update
  set day = excluded.day, starts_at = excluded.starts_at, status = excluded.status,
      home_team_id = excluded.home_team_id, away_team_id = excluded.away_team_id,
      home_score = excluded.home_score, away_score = excluded.away_score, detail = excluded.detail
  where (games.day, games.starts_at, games.status, games.detail, games.home_score, games.away_score)
        <> (excluded.day, excluded.starts_at, excluded.status, excluded.detail, excluded.home_score, excluded.away_score)
     or games.home_team_id is distinct from excluded.home_team_id
     or games.away_team_id is distinct from excluded.away_team_id
`

type UpsertGameParams struct {
	Competition string             `json:"competition"`
	ProviderID  string             `json:"provider_id"`
	Day         pgtype.Date        `json:"day"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	Status      string             `json:"status"`
	HomeTeamID  pgtype.UUID        `json:"home_team_id"`
	AwayTeamID  pgtype.UUID        `json:"away_team_id"`
	HomeScore   int32              `json:"home_score"`
	AwayScore   int32              `json:"away_score"`
	Detail      string             `json:"detail"`
}

// An unchanged game is not written again: every write here starts a new
// cache generation.
func (q *Queries) UpsertGame(ctx context.Context, arg UpsertGameParams) error {
	_, err := q.db.Exec(ctx, upsertGame,
		arg.Competition,
		arg.ProviderID,
		arg.Day,
		arg.StartsAt,
		arg.Status,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.HomeScore,
		arg.AwayScore,
		arg.Detail,
	)
	return err
}

const upsertStatLine = `-- name: UpsertStatLine :exec
insert into stat_lines (game_id, player_id, stats) values ($1, $2, $3)
on conflict (game_id, player_id) do update set stats = excluded.stats
  where stat_lines.stats is distinct from excluded.stats
`

type UpsertStatLineParams struct {
	GameID   pgtype.UUID     `json:"game_id"`
	PlayerID pgtype.UUID     `json:"player_id"`
	Stats    json.RawMessage `json:"stats"`
}

func (q *Queries) UpsertStatLine(ctx context.Context, arg UpsertStatLineParams) error {
	_, err := q.db.Exec(ctx, upsertStatLine, arg.GameID, arg.PlayerID, arg.Stats)
	return err
}
