// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seasons.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStalePlayerSeasons = `-- name: DeleteStalePlayerSeasons :exec
delete from player_seasons
where competition = $1 and year = $2 and league = '' and synced_at < $3
`

type DeleteStalePlayerSeasonsParams struct {
	Competition  string             `json:"competition"`
	Year         int32              `json:"year"`
	SyncedBefore pgtype.Timestamptz `json:"synced_before"`
}

// Removes a season's own-league lines that the latest sync did not write
// again: a traded player's line under his old team, for instance.
func (q *Queries) DeleteStalePlayerSeasons(ctx context.Context, arg DeleteStalePlayerSeasonsParams) error {
	_, err := q.db.Exec(ctx, deleteStalePlayerSeasons, arg.Competition, arg.Year, arg.SyncedBefore)
	return err
}

const listPlayerSeasons = `-- name: ListPlayerSeasons :many
select player_id, competition, year, label, team, league, games, stats, synced_at from player_seasons
where player_id = $1
order by year desc, league <> '', competition, team
`

// A player's seasons, newest first. Within a year his own league comes
// before any other.
func (q *Queries) ListPlayerSeasons(ctx context.Context, playerID pgtype.UUID) ([]PlayerSeason, error) {
	rows, err := q.db.Query(ctx, listPlayerSeasons, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerSeason{}
	for rows.Next() {
		var i PlayerSeason
		if err := rows.Scan(
			&i.PlayerID,
			&i.Competition,
			&i.Year,
			&i.Label,
			&i.Team,
			&i.League,
			&i.Games,
			&i.Stats,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonYears = `-- name: ListSeasonYears :many
select distinct year from player_seasons where competition = $1 and league = ''
`

// The seasons already stored for a competition's own league.
func (q *Queries) ListSeasonYears(ctx context.Context, competition string) ([]int32, error) {
	rows, err := q.db.Query(ctx, listSeasonYears, competition)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var year int32
		if err := rows.Scan(&year); err != nil {
			return nil, err
		}
		items = append(items, year)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCareerChecked = `-- name: MarkCareerChecked :exec
update players set career_checked_at = now() where id = $1
`

func (q *Queries) MarkCareerChecked(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markCareerChecked, id)
	return err
}

const movePlayerSeasons = `-- name: MovePlayerSeasons :exec
update player_seasons ps set player_id = $1
where ps.player_id = $2
  and not exists (
    select 1 from player_seasons k
    where k.player_id = $1 and k.competition = ps.competition and k.year = ps.year
      and k.team = ps.team and k.league = ps.league)
`

type MovePlayerSeasonsParams struct {
	KeepID      pgtype.UUID `json:"keep_id"`
	DuplicateID pgtype.UUID `json:"duplicate_id"`
}

// Keeps the surviving player's own line where both have one.
func (q *Queries) MovePlayerSeasons(ctx context.Context, arg MovePlayerSeasonsParams) error {
	_, err := q.db.Exec(ctx, movePlayerSeasons, arg.KeepID, arg.DuplicateID)
	return err
}

const upsertPlayerSeason = `-- name: UpsertPlayerSeason :exec
insert into player_seasons (player_id, competition, year, label, team, league, games, stats)
values ($1, $2, $3, $4, $5, $6, $7, $8)
on conflict (player_id, competition, year, team, league) do update
  set label = excluded.label, games = excluded.games, stats = excluded.stats, synced_at = now()
`

type UpsertPlayerSeasonParams struct {
	PlayerID    pgtype.UUID     `json:"player_id"`
	Competition string          `json:"competition"`
	Year        int32           `json:"year"`
	Label       string          `json:"label"`
	Team        string          `json:"team"`
	League      string          `json:"league"`
	Games       int32           `json:"games"`
	Stats       json.RawMessage `json:"stats"`
}

func (q *Queries) UpsertPlayerSeason(ctx context.Context, arg UpsertPlayerSeasonParams) error {
	_, err := q.db.Exec(ctx, upsertPlayerSeason,
		arg.PlayerID,
		arg.Competition,
		arg.Year,
		arg.Label,
		arg.Team,
		arg.League,
		arg.Games,
		arg.Stats,
	)
	return err
}
