// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trade.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptTrade = `-- name: AcceptTrade :exec
update trade_parties set accepted_at = now() where trade_id = $1 and franchise_id = $2
`

type AcceptTradeParams struct {
	TradeID     pgtype.UUID `json:"trade_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
}

func (q *Queries) AcceptTrade(ctx context.Context, arg AcceptTradeParams) error {
	_, err := q.db.Exec(ctx, acceptTrade, arg.TradeID, arg.FranchiseID)
	return err
}

const addTradeItem = `-- name: AddTradeItem :exec
insert into trade_items (trade_id, from_franchise, to_franchise, league_id, player_id, draft_pick_id)
values ($1, $2, $3, $4, $5, $6)
`

type AddTradeItemParams struct {
	TradeID       pgtype.UUID `json:"trade_id"`
	FromFranchise pgtype.UUID `json:"from_franchise"`
	ToFranchise   pgtype.UUID `json:"to_franchise"`
	LeagueID      pgtype.UUID `json:"league_id"`
	PlayerID      pgtype.UUID `json:"player_id"`
	DraftPickID   pgtype.UUID `json:"draft_pick_id"`
}

func (q *Queries) AddTradeItem(ctx context.Context, arg AddTradeItemParams) error {
	_, err := q.db.Exec(ctx, addTradeItem,
		arg.TradeID,
		arg.FromFranchise,
		arg.ToFranchise,
		arg.LeagueID,
		arg.PlayerID,
		arg.DraftPickID,
	)
	return err
}

const addTradeParty = `-- name: AddTradeParty :exec
insert into trade_parties (trade_id, franchise_id, accepted_at) values ($1, $2, $3)
`

type AddTradePartyParams struct {
	TradeID     pgtype.UUID        `json:"trade_id"`
	FranchiseID pgtype.UUID        `json:"franchise_id"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
}

func (q *Queries) AddTradeParty(ctx context.Context, arg AddTradePartyParams) error {
	_, err := q.db.Exec(ctx, addTradeParty, arg.TradeID, arg.FranchiseID, arg.AcceptedAt)
	return err
}

const createTrade = `-- name: CreateTrade :one
insert into trades (dynasty_id, proposed_by, note) values ($1, $2, $3) returning id, dynasty_id, status, proposed_by, note, created_at, resolved_at
`

type CreateTradeParams struct {
	DynastyID  pgtype.UUID `json:"dynasty_id"`
	ProposedBy pgtype.UUID `json:"proposed_by"`
	Note       string      `json:"note"`
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error) {
	row := q.db.QueryRow(ctx, createTrade, arg.DynastyID, arg.ProposedBy, arg.Note)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.DynastyID,
		&i.Status,
		&i.ProposedBy,
		&i.Note,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listDraftPickLeagues = `-- name: ListDraftPickLeagues :many
select l.id, l.dynasty_id, l.competition, l.name, l.settings, l.last_draft_at from leagues l
join draft_leagues dl on dl.league_id = l.id
join draft_picks k on k.draft_id = dl.draft_id
where k.id = $1
`

// The leagues a pick's draft covers.
func (q *Queries) ListDraftPickLeagues(ctx context.Context, id pgtype.UUID) ([]League, error) {
	rows, err := q.db.Query(ctx, listDraftPickLeagues, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []League{}
	for rows.Next() {
		var i League
		if err := rows.Scan(
			&i.ID,
			&i.DynastyID,
			&i.Competition,
			&i.Name,
			&i.Settings,
			&i.LastDraftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFranchisePicks = `-- name: ListFranchisePicks :many
select k.id, k.round, k.position, k.original_franchise_id,
       d.id as draft_id, d.name as draft_name, d.year, d.status as draft_status,
       (select coalesce(array_agg(l.competition), '{}')::text[]
        from draft_leagues dl join leagues l on l.id = dl.league_id
        where dl.draft_id = d.id) as competitions
from draft_picks k
join drafts d on d.id = k.draft_id
where k.current_franchise_id = $1 and k.player_id is null and d.status <> 'complete'
order by d.year, d.name, k.position
`

type ListFranchisePicksRow struct {
	ID                  pgtype.UUID `json:"id"`
	Round               int32       `json:"round"`
	Position            int32       `json:"position"`
	OriginalFranchiseID pgtype.UUID `json:"original_franchise_id"`
	DraftID             pgtype.UUID `json:"draft_id"`
	DraftName           string      `json:"draft_name"`
	Year                int32       `json:"year"`
	DraftStatus         string      `json:"draft_status"`
	Competitions        []string    `json:"competitions"`
}

// Unused picks a franchise holds, soonest draft first.
func (q *Queries) ListFranchisePicks(ctx context.Context, franchiseID pgtype.UUID) ([]ListFranchisePicksRow, error) {
	rows, err := q.db.Query(ctx, listFranchisePicks, franchiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFranchisePicksRow{}
	for rows.Next() {
		var i ListFranchisePicksRow
		if err := rows.Scan(
			&i.ID,
			&i.Round,
			&i.Position,
			&i.OriginalFranchiseID,
			&i.DraftID,
			&i.DraftName,
			&i.Year,
			&i.DraftStatus,
			&i.Competitions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradeItems = `-- name: ListTradeItems :many
select i.id, i.trade_id, i.from_franchise, i.to_franchise, i.league_id, i.player_id, i.draft_pick_id,
       coalesce(p.full_name, '')::text     as player_name,
       coalesce(p.positions, '{}')::text[] as player_positions,
       coalesce(p.headshot_url, '')::text  as player_headshot,
       coalesce(l.competition, '')::text   as competition,
       coalesce(d.name, '')::text          as draft_name,
       coalesce(k.round, 0)::int           as pick_round,
       k.original_franchise_id             as pick_original_franchise_id
from trade_items i
join trades t on t.id = i.trade_id
left join players p     on p.id = i.player_id
left join leagues l     on l.id = i.league_id
left join draft_picks k on k.id = i.draft_pick_id
left join drafts d      on d.id = k.draft_id
where t.dynasty_id = $1
order by i.id
`

type ListTradeItemsRow struct {
	ID                      pgtype.UUID `json:"id"`
	TradeID                 pgtype.UUID `json:"trade_id"`
	FromFranchise           pgtype.UUID `json:"from_franchise"`
	ToFranchise             pgtype.UUID `json:"to_franchise"`
	LeagueID                pgtype.UUID `json:"league_id"`
	PlayerID                pgtype.UUID `json:"player_id"`
	DraftPickID             pgtype.UUID `json:"draft_pick_id"`
	PlayerName              string      `json:"player_name"`
	PlayerPositions         []string    `json:"player_positions"`
	PlayerHeadshot          string      `json:"player_headshot"`
	Competition             string      `json:"competition"`
	DraftName               string      `json:"draft_name"`
	PickRound               int32       `json:"pick_round"`
	PickOriginalFranchiseID pgtype.UUID `json:"pick_original_franchise_id"`
}

// Every item of every trade in the dynasty, described for display.
func (q *Queries) ListTradeItems(ctx context.Context, dynastyID pgtype.UUID) ([]ListTradeItemsRow, error) {
	rows, err := q.db.Query(ctx, listTradeItems, dynastyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTradeItemsRow{}
	for rows.Next() {
		var i ListTradeItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TradeID,
			&i.FromFranchise,
			&i.ToFranchise,
			&i.LeagueID,
			&i.PlayerID,
			&i.DraftPickID,
			&i.PlayerName,
			&i.PlayerPositions,
			&i.PlayerHeadshot,
			&i.Competition,
			&i.DraftName,
			&i.PickRound,
			&i.PickOriginalFranchiseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradeItemsOf = `-- name: ListTradeItemsOf :many
select id, trade_id, from_franchise, to_franchise, league_id, player_id, draft_pick_id from trade_items where trade_id = $1 order by id
`

func (q *Queries) ListTradeItemsOf(ctx context.Context, tradeID pgtype.UUID) ([]TradeItem, error) {
	rows, err := q.db.Query(ctx, listTradeItemsOf, tradeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TradeItem{}
	for rows.Next() {
		var i TradeItem
		if err := rows.Scan(
			&i.ID,
			&i.TradeID,
			&i.FromFranchise,
			&i.ToFranchise,
			&i.LeagueID,
			&i.PlayerID,
			&i.DraftPickID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradeParties = `-- name: ListTradeParties :many
select p.trade_id, p.franchise_id, p.accepted_at from trade_parties p
join trades t on t.id = p.trade_id
where t.dynasty_id = $1
`

func (q *Queries) ListTradeParties(ctx context.Context, dynastyID pgtype.UUID) ([]TradeParty, error) {
	rows, err := q.db.Query(ctx, listTradeParties, dynastyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TradeParty{}
	for rows.Next() {
		var i TradeParty
		if err := rows.Scan(&i.TradeID, &i.FranchiseID, &i.AcceptedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradePartiesOf = `-- name: ListTradePartiesOf :many
select trade_id, franchise_id, accepted_at from trade_parties where trade_id = $1
`

func (q *Queries) ListTradePartiesOf(ctx context.Context, tradeID pgtype.UUID) ([]TradeParty, error) {
	rows, err := q.db.Query(ctx, listTradePartiesOf, tradeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TradeParty{}
	for rows.Next() {
		var i TradeParty
		if err := rows.Scan(&i.TradeID, &i.FranchiseID, &i.AcceptedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrades = `-- name: ListTrades :many
select id, dynasty_id, status, proposed_by, note, created_at, resolved_at from trades where dynasty_id = $1 order by created_at desc limit 200
`

func (q *Queries) ListTrades(ctx context.Context, dynastyID pgtype.UUID) ([]Trade, error) {
	rows, err := q.db.Query(ctx, listTrades, dynastyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trade{}
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.DynastyID,
			&i.Status,
			&i.ProposedBy,
			&i.Note,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDraftPick = `-- name: LockDraftPick :one
select k.id, k.draft_id, k.round, k.position, k.original_franchise_id, k.current_franchise_id, k.player_id, k.league_id, k.picked_at, k.auto_picked, k.skipped_at, k.passed_at, d.status as draft_status
from draft_picks k
join drafts d on d.id = k.draft_id
where k.id = $1
for update of k
`

type LockDraftPickRow struct {
	ID                  pgtype.UUID        `json:"id"`
	DraftID             pgtype.UUID        `json:"draft_id"`
	Round               int32              `json:"round"`
	Position            int32              `json:"position"`
	OriginalFranchiseID pgtype.UUID        `json:"original_franchise_id"`
	CurrentFranchiseID  pgtype.UUID        `json:"current_franchise_id"`
	PlayerID            pgtype.UUID        `json:"player_id"`
	LeagueID            pgtype.UUID        `json:"league_id"`
	PickedAt            pgtype.Timestamptz `json:"picked_at"`
	AutoPicked          bool               `json:"auto_picked"`
	SkippedAt           pgtype.Timestamptz `json:"skipped_at"`
	PassedAt            pgtype.Timestamptz `json:"passed_at"`
	DraftStatus         string             `json:"draft_status"`
}

// A pick with the state of its draft, locked for a trade.
func (q *Queries) LockDraftPick(ctx context.Context, id pgtype.UUID) (LockDraftPickRow, error) {
	row := q.db.QueryRow(ctx, lockDraftPick, id)
	var i LockDraftPickRow
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.Round,
		&i.Position,
		&i.OriginalFranchiseID,
		&i.CurrentFranchiseID,
		&i.PlayerID,
		&i.LeagueID,
		&i.PickedAt,
		&i.AutoPicked,
		&i.SkippedAt,
		&i.PassedAt,
		&i.DraftStatus,
	)
	return i, err
}

const lockTrade = `-- name: LockTrade :one
select id, dynasty_id, status, proposed_by, note, created_at, resolved_at from trades where id = $1 for update
`

func (q *Queries) LockTrade(ctx context.Context, id pgtype.UUID) (Trade, error) {
	row := q.db.QueryRow(ctx, lockTrade, id)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.DynastyID,
		&i.Status,
		&i.ProposedBy,
		&i.Note,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const moveTradeItems = `-- name: MoveTradeItems :exec
update trade_items set player_id = $1 where player_id = $2
`

type MoveTradeItemsParams struct {
	KeepID      pgtype.UUID `json:"keep_id"`
	DuplicateID pgtype.UUID `json:"duplicate_id"`
}

func (q *Queries) MoveTradeItems(ctx context.Context, arg MoveTradeItemsParams) error {
	_, err := q.db.Exec(ctx, moveTradeItems, arg.KeepID, arg.DuplicateID)
	return err
}

const seasonalDraftExists = `-- name: SeasonalDraftExists :one
select exists (
  select 1 from drafts d
  join draft_leagues dl on dl.draft_id = d.id
  where dl.league_id = $1 and d.kind = 'seasonal' and d.year = $2
)
`

type SeasonalDraftExistsParams struct {
	LeagueID pgtype.UUID `json:"league_id"`
	Year     int32       `json:"year"`
}

func (q *Queries) SeasonalDraftExists(ctx context.Context, arg SeasonalDraftExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, seasonalDraftExists, arg.LeagueID, arg.Year)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setDraftPickOwner = `-- name: SetDraftPickOwner :exec
update draft_picks set current_franchise_id = $1 where id = $2
`

type SetDraftPickOwnerParams struct {
	FranchiseID pgtype.UUID `json:"franchise_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) SetDraftPickOwner(ctx context.Context, arg SetDraftPickOwnerParams) error {
	_, err := q.db.Exec(ctx, setDraftPickOwner, arg.FranchiseID, arg.ID)
	return err
}

const setRosterOwner = `-- name: SetRosterOwner :exec
update roster_entries set franchise_id = $1, acquired_via = 'trade', acquired_at = now()
where league_id = $2 and player_id = $3
`

type SetRosterOwnerParams struct {
	ToFranchise pgtype.UUID `json:"to_franchise"`
	LeagueID    pgtype.UUID `json:"league_id"`
	PlayerID    pgtype.UUID `json:"player_id"`
}

func (q *Queries) SetRosterOwner(ctx context.Context, arg SetRosterOwnerParams) error {
	_, err := q.db.Exec(ctx, setRosterOwner, arg.ToFranchise, arg.LeagueID, arg.PlayerID)
	return err
}

const setTradeStatus = `-- name: SetTradeStatus :exec
update trades set
  status      = $1,
  resolved_at = case when $1 in ('proposed', 'accepted') then null else now() end
where id = $2
`

type SetTradeStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) SetTradeStatus(ctx context.Context, arg SetTradeStatusParams) error {
	_, err := q.db.Exec(ctx, setTradeStatus, arg.Status, arg.ID)
	return err
}
