// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: waiver.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelWaiverClaim = `-- name: CancelWaiverClaim :execrows
update waiver_claims set status = 'cancelled', resolved_at = now()
where id = $1 and franchise_id = $2 and status = 'pending'
`

type CancelWaiverClaimParams struct {
	ID          pgtype.UUID `json:"id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
}

func (q *Queries) CancelWaiverClaim(ctx context.Context, arg CancelWaiverClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelWaiverClaim, arg.ID, arg.FranchiseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearWaiverOrder = `-- name: ClearWaiverOrder :exec
delete from waiver_order where league_id = $1
`

func (q *Queries) ClearWaiverOrder(ctx context.Context, leagueID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearWaiverOrder, leagueID)
	return err
}

const countAcquisitions = `-- name: CountAcquisitions :one
select count(*) from transactions
where league_id = $1 and franchise_id = $2
  and kind in ('add', 'claim') and created_at >= $3
  and coalesce((detail->>'forced')::boolean, false) = false
`

type CountAcquisitionsParams struct {
	LeagueID    pgtype.UUID        `json:"league_id"`
	FranchiseID pgtype.UUID        `json:"franchise_id"`
	Since       pgtype.Timestamptz `json:"since"`
}

// Free agent adds and waiver claims a franchise has made itself since a
// moment; a commissioner's placements do not count.
func (q *Queries) CountAcquisitions(ctx context.Context, arg CountAcquisitionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAcquisitions, arg.LeagueID, arg.FranchiseID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteWaiver = `-- name: DeleteWaiver :exec
delete from waivers where league_id = $1 and player_id = $2
`

type DeleteWaiverParams struct {
	LeagueID pgtype.UUID `json:"league_id"`
	PlayerID pgtype.UUID `json:"player_id"`
}

func (q *Queries) DeleteWaiver(ctx context.Context, arg DeleteWaiverParams) error {
	_, err := q.db.Exec(ctx, deleteWaiver, arg.LeagueID, arg.PlayerID)
	return err
}

const getWaiver = `-- name: GetWaiver :one
select league_id, player_id, clears_at from waivers where league_id = $1 and player_id = $2
`

type GetWaiverParams struct {
	LeagueID pgtype.UUID `json:"league_id"`
	PlayerID pgtype.UUID `json:"player_id"`
}

func (q *Queries) GetWaiver(ctx context.Context, arg GetWaiverParams) (Waiver, error) {
	row := q.db.QueryRow(ctx, getWaiver, arg.LeagueID, arg.PlayerID)
	var i Waiver
	err := row.Scan(&i.LeagueID, &i.PlayerID, &i.ClearsAt)
	return i, err
}

const insertWaiverOrder = `-- name: InsertWaiverOrder :exec
insert into waiver_order (league_id, franchise_id, position) values ($1, $2, $3)
`

type InsertWaiverOrderParams struct {
	LeagueID    pgtype.UUID `json:"league_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
	Position    int32       `json:"position"`
}

func (q *Queries) InsertWaiverOrder(ctx context.Context, arg InsertWaiverOrderParams) error {
	_, err := q.db.Exec(ctx, insertWaiverOrder, arg.LeagueID, arg.FranchiseID, arg.Position)
	return err
}

const listDueWaivers = `-- name: ListDueWaivers :many
select league_id, player_id, clears_at from waivers where clears_at <= now() order by clears_at
`

func (q *Queries) ListDueWaivers(ctx context.Context) ([]Waiver, error) {
	rows, err := q.db.Query(ctx, listDueWaivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Waiver{}
	for rows.Next() {
		var i Waiver
		if err := rows.Scan(&i.LeagueID, &i.PlayerID, &i.ClearsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFranchiseClaims = `-- name: ListFranchiseClaims :many
select c.id, c.player_id, c.bid, c.list, c.status, c.reason, c.created_at, c.resolved_at,
       p.full_name as player_name,
       coalesce(d.full_name, '')::text as drop_player_name
from waiver_claims c
join players p on p.id = c.player_id
left join players d on d.id = c.drop_player_id
where c.league_id = $1 and c.franchise_id = $2 and c.status <> 'cancelled'
order by (c.status = 'pending') desc, coalesce(c.resolved_at, c.created_at) desc
limit 30
`

type ListFranchiseClaimsParams struct {
	LeagueID    pgtype.UUID `json:"league_id"`
	FranchiseID pgtype.UUID `json:"franchise_id"`
}

type ListFranchiseClaimsRow struct {
	ID             pgtype.UUID        `json:"id"`
	PlayerID       pgtype.UUID        `json:"player_id"`
	Bid            int32              `json:"bid"`
	List           string             `json:"list"`
	Status         string             `json:"status"`
	Reason         string             `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	PlayerName     string             `json:"player_name"`
	DropPlayerName string             `json:"drop_player_name"`
}

// A franchise's live claims, then the ones settled most recently.
func (q *Queries) ListFranchiseClaims(ctx context.Context, arg ListFranchiseClaimsParams) ([]ListFranchiseClaimsRow, error) {
	rows, err := q.db.Query(ctx, listFranchiseClaims, arg.LeagueID, arg.FranchiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFranchiseClaimsRow{}
	for rows.Next() {
		var i ListFranchiseClaimsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Bid,
			&i.List,
			&i.Status,
			&i.Reason,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.PlayerName,
			&i.DropPlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingClaims = `-- name: ListPendingClaims :many
select id, league_id, franchise_id, player_id, drop_player_id, bid, status, reason, created_at, resolved_at, list from waiver_claims
where league_id = $1 and player_id = $2 and status = 'pending'
order by created_at
`

type ListPendingClaimsParams struct {
	LeagueID pgtype.UUID `json:"league_id"`
	PlayerID pgtype.UUID `json:"player_id"`
}

func (q *Queries) ListPendingClaims(ctx context.Context, arg ListPendingClaimsParams) ([]WaiverClaim, error) {
	rows, err := q.db.Query(ctx, listPendingClaims, arg.LeagueID, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaiverClaim{}
	for rows.Next() {
		var i WaiverClaim
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.FranchiseID,
			&i.PlayerID,
			&i.DropPlayerID,
			&i.Bid,
			&i.Status,
			&i.Reason,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.List,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaiverStandings = `-- name: ListWaiverStandings :many
select f.id as franchise_id, f.name, f.slug,
       coalesce((select sum(c.bid) from waiver_claims c
                 where c.franchise_id = f.id and c.league_id = $1 and c.status = 'won'
                   and c.resolved_at >= coalesce(
                     (select max(s.starts_on) from seasons s where s.league_id = $1 and s.starts_on <= current_date)::timestamptz,
                     '-infinity')), 0)::int as spent
from franchises f
left join waiver_order o on o.franchise_id = f.id and o.league_id = $1
where f.dynasty_id = $2
order by o.position nulls last, f.name
`

type ListWaiverStandingsParams struct {
	LeagueID  pgtype.UUID `json:"league_id"`
	DynastyID pgtype.UUID `json:"dynasty_id"`
}

type ListWaiverStandingsRow struct {
	FranchiseID pgtype.UUID `json:"franchise_id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Spent       int32       `json:"spent"`
}

// Every franchise in one league's waiver order, first claim first. A
// franchise the order does not name yet (one added since it was set) comes
// last. spent is what its winning bids have cost since the league's
// current season began.
func (q *Queries) ListWaiverStandings(ctx context.Context, arg ListWaiverStandingsParams) ([]ListWaiverStandingsRow, error) {
	rows, err := q.db.Query(ctx, listWaiverStandings, arg.LeagueID, arg.DynastyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWaiverStandingsRow{}
	for rows.Next() {
		var i ListWaiverStandingsRow
		if err := rows.Scan(
			&i.FranchiseID,
			&i.Name,
			&i.Slug,
			&i.Spent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaivers = `-- name: ListWaivers :many
select w.player_id, w.clears_at, p.full_name, p.positions, p.status, p.note, p.headshot_url,
       coalesce(t.abbrev, '')::text as team_abbrev
from waivers w
join players p on p.id = w.player_id
left join pro_teams t on t.id = p.pro_team_id
where w.league_id = $1
order by w.clears_at, p.full_name
`

type ListWaiversRow struct {
	PlayerID    pgtype.UUID        `json:"player_id"`
	ClearsAt    pgtype.Timestamptz `json:"clears_at"`
	FullName    string             `json:"full_name"`
	Positions   []string           `json:"positions"`
	Status      string             `json:"status"`
	Note        string             `json:"note"`
	HeadshotUrl string             `json:"headshot_url"`
	TeamAbbrev  string             `json:"team_abbrev"`
}

func (q *Queries) ListWaivers(ctx context.Context, leagueID pgtype.UUID) ([]ListWaiversRow, error) {
	rows, err := q.db.Query(ctx, listWaivers, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWaiversRow{}
	for rows.Next() {
		var i ListWaiversRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.ClearsAt,
			&i.FullName,
			&i.Positions,
			&i.Status,
			&i.Note,
			&i.HeadshotUrl,
			&i.TeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putOnWaivers = `-- name: PutOnWaivers :exec
insert into waivers (league_id, player_id, clears_at)
values ($1, $2, $3)
on conflict (league_id, player_id) do update set clears_at = excluded.clears_at
`

type PutOnWaiversParams struct {
	LeagueID pgtype.UUID        `json:"league_id"`
	PlayerID pgtype.UUID        `json:"player_id"`
	ClearsAt pgtype.Timestamptz `json:"clears_at"`
}

func (q *Queries) PutOnWaivers(ctx context.Context, arg PutOnWaiversParams) error {
	_, err := q.db.Exec(ctx, putOnWaivers, arg.LeagueID, arg.PlayerID, arg.ClearsAt)
	return err
}

const putWaiverClaim = `-- name: PutWaiverClaim :exec
insert into waiver_claims (league_id, franchise_id, player_id, drop_player_id, bid, list)
values ($1, $2, $3, $4, $5, $6)
on conflict (league_id, franchise_id, player_id) where status = 'pending'
do update set drop_player_id = excluded.drop_player_id, bid = excluded.bid, list = excluded.list, created_at = now()
`

type PutWaiverClaimParams struct {
	LeagueID     pgtype.UUID `json:"league_id"`
	FranchiseID  pgtype.UUID `json:"franchise_id"`
	PlayerID     pgtype.UUID `json:"player_id"`
	DropPlayerID pgtype.UUID `json:"drop_player_id"`
	Bid          int32       `json:"bid"`
	List         string      `json:"list"`
}

// A franchise has one live claim per player; claiming again replaces it.
func (q *Queries) PutWaiverClaim(ctx context.Context, arg PutWaiverClaimParams) error {
	_, err := q.db.Exec(ctx, putWaiverClaim,
		arg.LeagueID,
		arg.FranchiseID,
		arg.PlayerID,
		arg.DropPlayerID,
		arg.Bid,
		arg.List,
	)
	return err
}

const resolveWaiverClaim = `-- name: ResolveWaiverClaim :exec
update waiver_claims set status = $1, reason = $2, resolved_at = now() where id = $3
`

type ResolveWaiverClaimParams struct {
	Status string      `json:"status"`
	Reason string      `json:"reason"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) ResolveWaiverClaim(ctx context.Context, arg ResolveWaiverClaimParams) error {
	_, err := q.db.Exec(ctx, resolveWaiverClaim, arg.Status, arg.Reason, arg.ID)
	return err
}
